var searchData=
[
  ['a_204th_20and_202nd_20order_20tensors_0',['Inner Product of a 4th and 2nd Order Tensors',['../group__TensorClass.html#TensorFuncs_prod42',1,'']]],
  ['a_20bug_1',['Status of a bug',['../Bugzilla.html#BugzStatus',1,'']]],
  ['a_20bugzilla_20query_2',['Setting up a Bugzilla Query',['../Bugzilla.html#BugzQuery',1,'']]],
  ['a_20communicator_3',['Adding a Communicator',['../group__CommOverview.html#CommAdd',1,'']]],
  ['a_20function_4',['How to Write a Function',['../group__WritingFunctions.html#WriteFunction',1,'']]],
  ['a_20ghost_20facet_5',['Determining who constructs a ghost facet',['../group__XTKGhost.html#XTKGhostRules',1,'']]],
  ['a_20library_6',['Add to a Library',['../group__WritingFunctions.html#LibrarySource',1,'']]],
  ['a_20linear_20system_20matrix_7',['Initialization of a Linear System Matrix',['../group__SpAlgPetsc.html#SpAlgPetscAllocMat',1,'']]],
  ['a_20main_8',['Setup a Main',['../group__CommOverview.html#CommMain',1,'']]],
  ['a_20new_20opt_20interface_9',['Adding a New OPT Interface',['../opt_framework_user.html#opt_interface_new',1,'']]],
  ['a_20new_20opt_20problem_10',['Adding a New OPT Problem',['../opt_framework_user.html#opt_problem_new',1,'']]],
  ['a_20package_11',['How to Add the First Library to a Package',['../group__AddingLibraries.html#FirstLibrary',1,'']]],
  ['a_20source_20file_20to_20the_20build_12',['Adding a Source File to the Build',['../group__WritingFunctions.html#CMakeSource',1,'']]],
  ['a_20sphere_202d_13',['a sphere 2d',['../EXA_OPTIMIZATION_THERMAL_FLOW_ABOUT_SPHERE_2D.html',1,'Thermal Flow about a sphere 2D'],['../EXA_OPTIMIZATION_THERMAL_TURBULENT_FLOW_ABOUT_SPHERE_2D.html',1,'Thermal Turbulent Flow about a sphere 2D']]],
  ['a_20sphere_203d_14',['Thermal Flow about a sphere 3D',['../EXA_OPTIMIZATION_THERMAL_FLOW_ABOUT_SPHERE_3D.html',1,'']]],
  ['a_20sweep_20and_20comparing_20results_15',['Running a Sweep and Comparing Results',['../UsingMoris.html#InputFileSweep',1,'']]],
  ['a_20tag_16',['Adding a Tag',['../BugReporting.html#BR_AddTag',1,'']]],
  ['a_20task_17',['a task',['../Bugzilla.html#BugzTask',1,'Making a Task'],['../Bugzilla.html#BugzRespond',1,'Responding to a Task']]],
  ['a_20test_18',['How to Write a Test',['../group__WritingTests.html#WriteTest',1,'']]],
  ['a_20test_20in_20cmake_19',['How to Add a Test in CMake',['../group__WritingTests.html#CMakeTest',1,'']]],
  ['a_20thermoelastic_20circle_20problem_20',['Shape Sensitivity of a Thermoelastic Circle Problem',['../EXA_OPTIMIZATION_SHAPE_SENS_CIRCLE_SWEEP_THERMOELASTIC.html',1,'']]],
  ['a_20thermoelastic_20two_20material_20problem_21',['Shape Sensitivity of a Thermoelastic Two Material Problem',['../EXA_OPTIMIZATION_SHAPE_SENS_TWO_MAT_SWEEP_THERMOELASTIC.html',1,'']]],
  ['a_20transient_20circle_20problem_22',['Shape Sensitivity of a Transient Circle Problem',['../EXA_OPTIMIZATION_SHAPE_SENS_CIRCLE_SWEEP_TRANSIENT.html',1,'']]],
  ['a_20transient_20thermoelastic_20circle_20problem_23',['Shape Sensitivity of a Transient Thermoelastic Circle Problem',['../EXA_OPTIMIZATION_SHAPE_SENS_CIRCLE_SWEEP_THERMOELASTIC_TRANSIENT.html',1,'']]],
  ['abbreviations_24',['Abbreviations',['../group__CodingStyle.html#Abv',1,'']]],
  ['about_20a_20sphere_202d_25',['about a sphere 2d',['../EXA_OPTIMIZATION_THERMAL_FLOW_ABOUT_SPHERE_2D.html',1,'Thermal Flow about a sphere 2D'],['../EXA_OPTIMIZATION_THERMAL_TURBULENT_FLOW_ABOUT_SPHERE_2D.html',1,'Thermal Turbulent Flow about a sphere 2D']]],
  ['about_20a_20sphere_203d_26',['Thermal Flow about a sphere 3D',['../EXA_OPTIMIZATION_THERMAL_FLOW_ABOUT_SPHERE_3D.html',1,'']]],
  ['about_20existing_20integration_20mesh_27',['about existing integration mesh',['../group__XTKDecomp.html#XTK_Decomp_ElevateOrder_CollectConnectivity',1,'Collecting Connectivity Information about Existing Integration Mesh'],['../group__XTKDecomp.html#XTK_Decomp_HierSub_CollectConnectivity',1,'Collecting Connectivity Information about Existing Integration Mesh'],['../group__XTKElevateOrder.html#Collect',1,'connectivity Information about Existing Integration Mesh']]],
  ['about_20new_20cells_28',['Necessary Information about new Cells',['../group__XTKElevateOrder.html#Computing',1,'']]],
  ['about_20new_20vertices_29',['Computing Necessary Information about new Vertices',['../group__XTKDecomp.html#XTK_Decomp_ElevateOrder_VertInfo',1,'']]],
  ['accepted_20environment_20variable_20formats_30',['Other Accepted Environment Variable Formats',['../BuildingMoris.html#OtherAcceptedEnvVars',1,'']]],
  ['accessing_20data_31',['Declaring and Accessing Data',['../group__TensorClass.html#TensorAccess',1,'']]],
  ['acoordinates_32',['moris::ge::Scaled_Field::get_base_field_value(&lt;optimized out&gt;,aNodeIndex,aCoordinates)',['../group__SegFaults.html#SegFault_GEN001',1,'']]],
  ['adaptive_20refinement_20problem_33',['adaptive refinement problem',['../EXA_OPTIMIZATION_LEVELSET_BOXBEAM_ADAPTIVE_REFINE.html',1,'Levelset Boxbeam With Adaptive Refinement Problem'],['../EXA_OPTIMIZATION_LEVELSET_BOXBEAM_ADAPTIVE_REFINE_RESTART.html',1,'Levelset Boxbeam With Restarted Adaptive Refinement Problem']]],
  ['add_20a_20test_20in_20cmake_34',['How to Add a Test in CMake',['../group__WritingTests.html#CMakeTest',1,'']]],
  ['add_20consecutive_20libraries_35',['How to Add Consecutive Libraries',['../group__AddingLibraries.html#ConsecutiveLibraries',1,'']]],
  ['add_20environment_20variables_36',['How to Add Environment Variables',['../BuildingMoris.html#AddEnvVars',1,'']]],
  ['add_20the_20first_20library_20to_20a_20package_37',['How to Add the First Library to a Package',['../group__AddingLibraries.html#FirstLibrary',1,'']]],
  ['add_20to_20a_20library_38',['Add to a Library',['../group__WritingFunctions.html#LibrarySource',1,'']]],
  ['add_20to_20an_20executable_39',['Add to an Executable',['../group__WritingFunctions.html#ExecutableSource',1,'']]],
  ['adding_20a_20communicator_40',['Adding a Communicator',['../group__CommOverview.html#CommAdd',1,'']]],
  ['adding_20a_20new_20opt_20interface_41',['Adding a New OPT Interface',['../opt_framework_user.html#opt_interface_new',1,'']]],
  ['adding_20a_20new_20opt_20problem_42',['Adding a New OPT Problem',['../opt_framework_user.html#opt_problem_new',1,'']]],
  ['adding_20a_20source_20file_20to_20the_20build_43',['Adding a Source File to the Build',['../group__WritingFunctions.html#CMakeSource',1,'']]],
  ['adding_20a_20tag_44',['Adding a Tag',['../BugReporting.html#BR_AddTag',1,'']]],
  ['adding_20executables_45',['Adding Executables',['../group__AddingExecutables.html',1,'']]],
  ['adding_20libraries_46',['Adding Libraries',['../group__AddingLibraries.html',1,'']]],
  ['adding_20projects_47',['Adding Projects',['../group__AddingProjects.html',1,'']]],
  ['additional_20executables_48',['Additional Executables',['../group__AddingExecutables.html#AdditonalExecutable',1,'']]],
  ['advection_49',['List of Examples and Benchmarks for Thermal Diffusion and Advection',['../group__EXA__THERMAL.html',1,'']]],
  ['advection_20reaction_20equations_50',['Diffusion-Advection-Reaction Equations',['../group__FE__Equations__Diffusion__Advection__Reaction.html',1,'']]],
  ['advective_20energy_20flux_20boundary_20iwg_51',['Advective Energy Flux Boundary IWG',['../group__FE__Compressible__NS.html#autotoc_md276',1,'']]],
  ['advective_20mass_20flux_20boundary_20iwg_52',['Advective Mass Flux Boundary IWG',['../group__FE__Compressible__NS.html#autotoc_md275',1,'']]],
  ['algebra_53',['algebra',['../group__LinAlg.html',1,'Linear Algebra'],['../group__SpAlg.html',1,'Sparse Algebra']]],
  ['algorithm_54',['algorithm',['../group__XTKDecomp.html#XTK_Decomp_ElevateOrder',1,'Elevate Order Algorithm'],['../opt_algorithm_developer.html',1,'OPT Algorithm'],['../group__CommOverview.html#CommAlg',1,'Using An MPI Tools Algorithm']]],
  ['algorithmically_55',['algorithmically',['../group__XTKDecomp.html#XTK_Decomp_Overview_Alg',1,'Algorithmically'],['../group__XTKDecomp.html#XTK_Decomp_Methods_Alg',1,'Algorithmically']]],
  ['algorithms_56',['OPT Algorithms',['../opt_framework_user.html#opt_algorithm_user',1,'']]],
  ['alignment_57',['Operator Alignment',['../group__CodingStyle.html#OpAlignment',1,'']]],
  ['allmaras_20model_58',['Negative Spalart-Allmaras Model',['../group__FE__Equations__Spalart__Allmaras__Turbulence.html#Negative_SA_Model',1,'']]],
  ['allmaras_20turbulence_20model_20equations_59',['Spalart-Allmaras Turbulence Model Equations',['../group__FE__Equations__Spalart__Allmaras__Turbulence.html',1,'']]],
  ['an_20evironmental_20variable_60',['Setting MORISROOT as an Evironmental Variable',['../GettingStarted.html#EnvVar',1,'']]],
  ['an_20example_61',['Creating an example',['../group__EXA__DEV__GUIDE.html#autotoc_md3',1,'']]],
  ['an_20executable_62',['Add to an Executable',['../group__WritingFunctions.html#ExecutableSource',1,'']]],
  ['an_20existing_20directory_20of_20files_20to_20the_20repository_63',['Importing an Existing Directory of Files to the Repository',['../SVNTopics.html#SVNImport',1,'']]],
  ['an_20input_20file_64',['Steps to Create an Input File',['../UsingMoris.html#InputFileSteps',1,'']]],
  ['an_20mpi_20tools_20algorithm_65',['Using An MPI Tools Algorithm',['../group__CommOverview.html#CommAlg',1,'']]],
  ['an_20optimization_20problem_66',['Formulating an Optimization Problem',['../opt_background.html#opt_formulation',1,'']]],
  ['analysis_67',['Sensitivity Analysis',['../opt_background.html#opt_sensitivity',1,'']]],
  ['analytical_20solution_68',['analytical solution',['../EXA_THERMAL_ADVECTION_CHANNEL_WITH_FOUR_CYLINDERS_STATIC.html#autotoc_md199',1,'Analytical Solution'],['../EXA_THERMAL_STEFANS_PROBLEM.html#autotoc_md229',1,'Analytical Solution'],['../EXA_Single_Phase_Hollow_Cylinder_Static.html#autotoc_md224',1,'Analytical Solution'],['../EXA_THERMAL_FICKIAN_PROBLEM.html#autotoc_md219',1,'Analytical Solution'],['../EXA_THERMAL_ADVECTION_TWO_CHANNELS.html#autotoc_md209',1,'Analytical Solution'],['../EXA_THERMAL_ADVECTION_CHANNEL_WITH_FOUR_CYLINDERS_TRANSIENT.html#autotoc_md204',1,'Analytical Solution'],['../EXA_SIMP.html#autotoc_md122',1,'Analytical Solution'],['../EXA_Shape_Sensitivity_Sweep.html#autotoc_md112',1,'Analytical Solution'],['../EXA_Shape_Sensitivity_Bspline.html#autotoc_md92',1,'Analytical Solution'],['../EXA_Couette_Flow_Static.html#autotoc_md20',1,'Analytical Solution'],['../EXA_Channel_2D_Static.html#autotoc_md15',1,'Analytical Solution'],['../EXA_THERMAL_GGLS_DEMO.html#autotoc_md10',1,'Analytical Solution']]],
  ['ancestry_69',['Ancestry',['../group__XTKDictionary.html#XTK_Ancestry',1,'']]],
  ['and_202nd_20order_20tensors_70',['Inner Product of a 4th and 2nd Order Tensors',['../group__TensorClass.html#TensorFuncs_prod42',1,'']]],
  ['and_20accessing_20data_71',['Declaring and Accessing Data',['../group__TensorClass.html#TensorAccess',1,'']]],
  ['and_20asserts_72',['Errors and Asserts',['../group__ErrorsAsserts.html',1,'']]],
  ['and_20benchmarks_73',['Examples and Benchmarks',['../group__EXA__Module.html',1,'']]],
  ['and_20benchmarks_20for_20fluid_20physics_74',['List of Examples and Benchmarks for Fluid Physics',['../group__EXA__FLUID.html',1,'']]],
  ['and_20benchmarks_20for_20shape_20and_20topology_20optimization_75',['List of Examples and Benchmarks for Shape and Topology Optimization',['../group__EXA__OPTIMIZATION.html',1,'']]],
  ['and_20benchmarks_20for_20structural_20problems_76',['List of Examples and Benchmarks for Structural Problems',['../group__EXA__STRUCTURAL.html',1,'']]],
  ['and_20benchmarks_20for_20thermal_20diffusion_20and_20advection_77',['List of Examples and Benchmarks for Thermal Diffusion and Advection',['../group__EXA__THERMAL.html',1,'']]],
  ['and_20commiting_20them_20to_20the_20mesh_78',['of new Cells and commiting them to the Mesh',['../group__XTKElevateOrder.html#Creation',1,'']]],
  ['and_20comparing_20results_79',['Running a Sweep and Comparing Results',['../UsingMoris.html#InputFileSweep',1,'']]],
  ['and_20epetra_5fvector_80',['Assembly from moris::mat to Epetra_FECrsMatrix and Epetra_Vector',['../group__SpAlgTrilinos.html#SpAlgTrilinosAssembly',1,'']]],
  ['and_20executable_20sections_81',['Library and Executable sections',['../group__AddingProjects.html#LibraryExecutableSec',1,'']]],
  ['and_20fem_82',['Draft: Interoperability between HMR, XTK and FEM',['../group__MTK__Interoperability.html',1,'']]],
  ['and_20geometry_20engine_83',['Geometry and Geometry Engine',['../group__XTKOverview.html#XTKGeometry',1,'']]],
  ['and_20installation_20sections_84',['Config File and Installation Sections',['../group__AddingProjects.html#ConfigInstallSec',1,'']]],
  ['and_20mapper_85',['Field and Mapper',['../group__MTK__Mapper.html',1,'']]],
  ['and_20moving_20files_20in_20eclipse_86',['Directories and Moving Files in Eclipse',['../SVNTopics.html#MovingFiles',1,'']]],
  ['and_20pages_87',['Modules and Pages',['../group__DocumentationStyle.html#WritingChapters',1,'']]],
  ['and_20procedures_88',['Bugzilla Installation, Setup, and Procedures',['../Bugzilla.html',1,'']]],
  ['and_20related_20functions_89',['The Tensor class and Related Functions',['../group__TensorClass.html',1,'']]],
  ['and_20rhs_20vectors_90',['Initialization of Solution and RHS Vectors',['../group__SpAlgPetsc.html#SpAlgPetscAllocVec',1,'']]],
  ['and_20running_20input_20files_91',['Compiling and Running Input Files',['../UsingMoris.html#InputFileCompileRun',1,'']]],
  ['and_20stresses_92',['Traction BC (Prescribe Pressure and stresses)',['../group__FE__Compressible__NS.html#autotoc_md278',1,'']]],
  ['and_20sub_20phase_20neighborhood_93',['and sub phase neighborhood',['../group__XTKConcepts.html#XTKBpSpSpNeigh',1,'Bulk-phase, Sub-phase and Sub-phase Neighborhood'],['../group__XTKDictionary.html#XTK_Phases',1,'Bulk-phase, Sub-phase and Sub-phase Neighborhood']]],
  ['and_20use_94',['Setup and Use',['../group__GE__setup.html',1,'']]],
  ['anodeindex_20acoordinates_95',['moris::ge::Scaled_Field::get_base_field_value(&lt;optimized out&gt;,aNodeIndex,aCoordinates)',['../group__SegFaults.html#SegFault_GEN001',1,'']]],
  ['appropriate_20hmr_20settings_96',['Appropriate HMR Settings',['../UsingMoris.html#InputFileHMRSettings',1,'']]],
  ['appropriate_20sol_20settings_97',['Appropriate SOL Settings',['../UsingMoris.html#InputFileSOLSettings',1,'']]],
  ['argument_20passing_98',['Argument Passing',['../group__CodingStyle.html#ArgPassing',1,'']]],
  ['as_20an_20evironmental_20variable_99',['Setting MORISROOT as an Evironmental Variable',['../GettingStarted.html#EnvVar',1,'']]],
  ['assembly_20from_20moris_3a_3amat_20to_20epetra_5ffecrsmatrix_20and_20epetra_5fvector_100',['Assembly from moris::mat to Epetra_FECrsMatrix and Epetra_Vector',['../group__SpAlgTrilinos.html#SpAlgTrilinosAssembly',1,'']]],
  ['asserts_101',['Errors and Asserts',['../group__ErrorsAsserts.html',1,'']]],
  ['asymptotes_20gcmma_102',['Globally Convergent Method of Moving Asymptotes (GCMMA)',['../opt_gcmma.html',1,'opt_module']]],
  ['at_20this_20function_3a_103',['FEM_Model::example_function - Failed at this function:',['../group__ErrorsAsserts.html#Error_test001',1,'']]],
  ['axisymmetric_20problem_104',['Axisymmetric Problem',['../EXA_Structure_Linear_Axisymmetric.html',1,'']]],
  ['axisymmetricproblem_105',['AxisymmetricProblem',['../EXA_Structure_Thermo_Elastic_MOPAR.html',1,'']]]
];
