var searchData=
[
  ['b_20spline_20mesh_0',['B-Spline Mesh',['../group__HMR__BSpline__Mesh.html',1,'']]],
  ['background_1',['Optimization Background',['../opt_background.html',1,'opt_module']]],
  ['background_20element_2',['Background Element',['../group__HMR__Background__Mesh.html#autotoc_md295',1,'']]],
  ['background_20mesh_3',['background mesh',['../group__XTKOverview.html#XTKBackgroundMesh',1,'Background Mesh'],['../group__XTKDictionary.html#XTK_Mesh_Background_Mesh',1,'Background Mesh'],['../group__HMR__Background__Mesh.html',1,'Background Mesh']]],
  ['background_20mesh_20refinement_4',['Background Mesh Refinement',['../group__HMR__Background__Mesh.html#autotoc_md296',1,'']]],
  ['bar_20static_20problem_5',['SA Cut Bar Static Problem',['../EXA_OPTIMIZATION_SA_CUT_BAR_STATIC.html',1,'']]],
  ['bar_20truss_6',['Two Bar Truss.',['../EXA_Structure_Linear_Two_Bar_Truss.html',1,'']]],
  ['base_20class_7',['Mesh Base Class',['../group__HMR__Base__Mesh.html',1,'']]],
  ['bc_8',['bc',['../FE_CM_Diffusion.html#autotoc_md249',1,'Dirichlet BC'],['../FE_CM_Diffusion.html#autotoc_md248',1,'Radiation BC'],['../FE_CM_Diffusion.html#autotoc_md247',1,'Robin BC'],['../FE_CM_Diffusion.html#autotoc_md250',1,'Robin BC'],['../FE_CM_Diffusion.html#autotoc_md246',1,'Von-Neumann BC']]],
  ['bc_20prescribe_20heat_20in_20out_20flow_9',['Thermal Neumann BC (Prescribe Heat in-/out-flow)',['../group__FE__Compressible__NS.html#autotoc_md280',1,'']]],
  ['bc_20prescribe_20mass_20in_20out_20flow_10',['Mass Flux Neumann BC (Prescribe Mass in-/out-flow)',['../group__FE__Compressible__NS.html#autotoc_md279',1,'']]],
  ['bc_20prescribe_20pressure_20and_20stresses_11',['Traction BC (Prescribe Pressure and stresses)',['../group__FE__Compressible__NS.html#autotoc_md278',1,'']]],
  ['beam_20simp_20hole_20seeding_12',['Levelset Beam SIMP Hole Seeding',['../EXA_OPTIMIZATION_SIMP_HOLE_SEEDING.html',1,'']]],
  ['beam_20temperature_20field_20problem_13',['Beam Temperature Field Problem.',['../EXA_Structure_Linear_Beam_Temperature_Field.html',1,'']]],
  ['bedding_20sensitivity_20problem_14',['Bedding Sensitivity Problem',['../EXA_OPTIMIZATION_BEDDDING_SENSITIVITY.html',1,'']]],
  ['before_20committing_15',['Before Committing',['../group__EclipseSVNCommands.html#CommitProcedure',1,'']]],
  ['benchmarks_16',['Examples and Benchmarks',['../group__EXA__Module.html',1,'']]],
  ['benchmarks_20examples_17',['Benchmarks/Examples',['../FE_CM_Diffusion.html#autotoc_md251',1,'']]],
  ['benchmarks_20for_20fluid_20physics_18',['List of Examples and Benchmarks for Fluid Physics',['../group__EXA__FLUID.html',1,'']]],
  ['benchmarks_20for_20shape_20and_20topology_20optimization_19',['List of Examples and Benchmarks for Shape and Topology Optimization',['../group__EXA__OPTIMIZATION.html',1,'']]],
  ['benchmarks_20for_20structural_20problems_20',['List of Examples and Benchmarks for Structural Problems',['../group__EXA__STRUCTURAL.html',1,'']]],
  ['benchmarks_20for_20thermal_20diffusion_20and_20advection_21',['List of Examples and Benchmarks for Thermal Diffusion and Advection',['../group__EXA__THERMAL.html',1,'']]],
  ['between_20hmr_20xtk_20and_20fem_22',['Draft: Interoperability between HMR, XTK and FEM',['../group__MTK__Interoperability.html',1,'']]],
  ['block_20gauss_20seidel_23',['Nonlinear Block Gauss Seidel',['../group__NLANLBGS.html',1,'']]],
  ['boundary_20condition_24',['Dirichlet Boundary Condition',['../group__FE__Dirichlet__BCs.html',1,'']]],
  ['boundary_20conditions_25',['IWGs for enforcing Boundary Conditions',['../group__FE__Compressible__NS.html#autotoc_md277',1,'']]],
  ['boundary_20conditions_20via_20nitsche_20s_20formulation_26',['Dirichlet Boundary Conditions via Nitsche&apos;s Formulation',['../group__FE__Equations__Spalart__Allmaras__Turbulence.html#Dirichlet_BC',1,'']]],
  ['boundary_20iwg_27',['boundary iwg',['../group__FE__Compressible__NS.html#autotoc_md276',1,'Advective Energy Flux Boundary IWG'],['../group__FE__Compressible__NS.html#autotoc_md275',1,'Advective Mass Flux Boundary IWG']]],
  ['boundary_20iwgs_28',['boundary iwgs',['../group__FE__Compressible__NS.html#autotoc_md274',1,'Boundary IWGs'],['../group__FE__Compressible__NS.html#autotoc_md269',1,'Boundary IWGs']]],
  ['boundary_20terms_20in_20the_20weak_20form_29',['Boundary Terms in the Weak Form',['../group__FE__Compressible__NS.html#autotoc_md270',1,'']]],
  ['boxbeam_20problem_30',['Levelset Boxbeam Problem',['../EXA_OPTIMIZATION_LEVELSET_BOXBEAM.html',1,'']]],
  ['boxbeam_20with_20adaptive_20refinement_20problem_31',['Levelset Boxbeam With Adaptive Refinement Problem',['../EXA_OPTIMIZATION_LEVELSET_BOXBEAM_ADAPTIVE_REFINE.html',1,'']]],
  ['boxbeam_20with_20restarted_20adaptive_20refinement_20problem_32',['Levelset Boxbeam With Restarted Adaptive Refinement Problem',['../EXA_OPTIMIZATION_LEVELSET_BOXBEAM_ADAPTIVE_REFINE_RESTART.html',1,'']]],
  ['breakdown_33',['Depends File Breakdown',['../ExplainUpperLevel.html#ExplainDepends',1,'']]],
  ['broyden_20fletcher_20goldfarb_20shanno_20lbfgs_34',['Limited-Memory Broyden-Fletcher-Goldfarb-Shanno (LBFGS)',['../opt_lbfgs.html',1,'opt_module']]],
  ['bug_35',['Status of a bug',['../Bugzilla.html#BugzStatus',1,'']]],
  ['bugs_36',['Reporting of Bugs',['../BugReporting.html',1,'MiscTopics']]],
  ['bugzilla_20installation_20setup_20and_20procedures_37',['Bugzilla Installation, Setup, and Procedures',['../Bugzilla.html',1,'']]],
  ['bugzilla_20query_38',['Setting up a Bugzilla Query',['../Bugzilla.html#BugzQuery',1,'']]],
  ['bugzilla_20repository_39',['Setting up the Bugzilla repository',['../Bugzilla.html#BugzSetup',1,'']]],
  ['build_40',['build',['../group__WritingFunctions.html#CMakeSource',1,'Adding a Source File to the Build'],['../MakefileWrapper.html#OutOfSourceBuild',1,'Out-of-source build']]],
  ['building_20moris_41',['Building MORIS',['../BuildingMoris.html',1,'']]],
  ['building_20your_20moris_20configuration_42',['Building your MORIS Configuration',['../BuildingMoris.html#MorisBuild',1,'']]],
  ['bulk_43',['Bulk',['../FE_CM_Diffusion.html#autotoc_md245',1,'']]],
  ['bulk_20iwgs_44',['Bulk IWGs',['../group__FE__Compressible__NS.html#autotoc_md263',1,'']]],
  ['bulk_20phase_20sub_20phase_20and_20sub_20phase_20neighborhood_45',['bulk phase sub phase and sub phase neighborhood',['../group__XTKDictionary.html#XTK_Phases',1,'Bulk-phase, Sub-phase and Sub-phase Neighborhood'],['../group__XTKConcepts.html#XTKBpSpSpNeigh',1,'Bulk-phase, Sub-phase and Sub-phase Neighborhood']]]
];
