var searchData=
[
  ['ideal_20gas_20model_0',['Ideal Gas Model',['../group__FE__Compressible__NS.html#autotoc_md258',1,'']]],
  ['if_20else_20statements_1',['If Else Statements',['../group__CodingStyle.html#IfElseStatements',1,'']]],
  ['ig_20cell_20groups_2',['IG-Cell Groups',['../group__XTKDictionary.html#XTK_Mesh_IG-Cell_Group',1,'']]],
  ['ignoring_20directories_20or_20files_3',['Ignoring Directories or Files',['../SVNTopics.html#SVNIgnore',1,'']]],
  ['implementation_4',['Implementation',['../group__XTKGhost.html#XTKGhostImplementation',1,'']]],
  ['implementation_20of_20grad_20div_20flux_5',['Implementation of Grad-Div-Flux',['../FE_CM_Diffusion.html#autotoc_md243',1,'']]],
  ['importing_20an_20existing_20directory_20of_20files_20to_20the_20repository_6',['Importing an Existing Directory of Files to the Repository',['../SVNTopics.html#SVNImport',1,'']]],
  ['improve_20optimization_20solutions_7',['Changes to Improve Optimization Solutions',['../UsingMoris.html#ConvergenceTweaks',1,'']]],
  ['in_8',['Installing the SVN Plug-In',['../SVNTopics.html#SVNInstall',1,'']]],
  ['in_202d_20problem_9',['Homogenization in 2D Problem.',['../EXA_Structure_Linear_Homogenization_2D.html',1,'']]],
  ['in_20cmake_10',['How to Add a Test in CMake',['../group__WritingTests.html#CMakeTest',1,'']]],
  ['in_20doxygen_11',['Linking in Doxygen',['../group__DocumentationStyle.html#DoxyLinks',1,'']]],
  ['in_20eclipse_12',['in eclipse',['../SVNTopics.html#MovingFiles',1,'Directories and Moving Files in Eclipse'],['../group__EclipseSVNCommands.html',1,'SVN Commands in Eclipse']]],
  ['in_20incompressible_20navier_20stokes_13',['Stabilization Parameter for SUPG stabilization in Incompressible Navier-Stokes',['../FE_SP_Incompressible_NS.html',1,'']]],
  ['in_20interface_20condition_14',['in interface condition',['../FE_SP_Follower_Weight_Interface.html',1,'Stabilization Parameter for Follower Weight in Interface condition'],['../FE_SP_Leader_Weight_Interface.html',1,'Stabilization Parameter for Leader Weight in Interface condition']]],
  ['in_20moris_15',['Optimization Framework in MORIS',['../opt_framework_user.html',1,'opt_module']]],
  ['in_20out_20flow_16',['in out flow',['../group__FE__Compressible__NS.html#autotoc_md279',1,'Mass Flux Neumann BC (Prescribe Mass in-/out-flow)'],['../group__FE__Compressible__NS.html#autotoc_md280',1,'Thermal Neumann BC (Prescribe Heat in-/out-flow)']]],
  ['in_20the_20code_17',['in the code',['../group__CodingStyle.html#Checks',1,'Checks in the code'],['../group__KnownIssues.html',1,'Known Issues in the Code']]],
  ['in_20the_20weak_20form_18',['Boundary Terms in the Weak Form',['../group__FE__Compressible__NS.html#autotoc_md270',1,'']]],
  ['include_20input_20file_20with_20catch_19',['Include Input file with CATCH',['../group__EXA__DEV__GUIDE.html#autotoc_md5',1,'']]],
  ['incompressible_20navier_20stokes_20',['Stabilization Parameter for SUPG stabilization in Incompressible Navier-Stokes',['../FE_SP_Incompressible_NS.html',1,'']]],
  ['incompressible_20navier_20stokes_20equations_21',['Incompressible Navier-Stokes Equations',['../group__FE__Equations__Incompressible__Navier__Stokes.html',1,'']]],
  ['information_20about_20existing_20integration_20mesh_22',['information about existing integration mesh',['../group__XTKDecomp.html#XTK_Decomp_HierSub_CollectConnectivity',1,'Collecting Connectivity Information about Existing Integration Mesh'],['../group__XTKDecomp.html#XTK_Decomp_ElevateOrder_CollectConnectivity',1,'Collecting Connectivity Information about Existing Integration Mesh'],['../group__XTKElevateOrder.html#Collect',1,'connectivity Information about Existing Integration Mesh']]],
  ['information_20about_20new_20cells_23',['Necessary Information about new Cells',['../group__XTKElevateOrder.html#Computing',1,'']]],
  ['information_20about_20new_20vertices_24',['Computing Necessary Information about new Vertices',['../group__XTKDecomp.html#XTK_Decomp_ElevateOrder_VertInfo',1,'']]],
  ['initial_20repository_20setup_25',['Initial Repository Setup',['../SVNTopics.html#InitRepSetup',1,'']]],
  ['initialization_26',['Initialization',['../group__HMR__Background__Mesh.html#autotoc_md294',1,'']]],
  ['initialization_20of_20a_20linear_20system_20matrix_27',['Initialization of a Linear System Matrix',['../group__SpAlgPetsc.html#SpAlgPetscAllocMat',1,'']]],
  ['initialization_20of_20petsc_28',['Initialization of Petsc',['../group__SpAlgPetsc.html#SpAlgPetscInit',1,'']]],
  ['initialization_20of_20solution_20and_20rhs_20vectors_29',['Initialization of Solution and RHS Vectors',['../group__SpAlgPetsc.html#SpAlgPetscAllocVec',1,'']]],
  ['initialization_20of_20trilinos_30',['Initialization of Trilinos',['../group__SpAlgTrilinos.html#SpAlgTrilinosInit',1,'']]],
  ['inner_20double_20dot_20product_31',['Double Inner (&quot;double dot&quot;) Product',['../group__TensorClass.html#TensorFuncs_DoubleInner',1,'']]],
  ['inner_20product_20of_20a_204th_20and_202nd_20order_20tensors_32',['Inner Product of a 4th and 2nd Order Tensors',['../group__TensorClass.html#TensorFuncs_prod42',1,'']]],
  ['input_20file_33',['Steps to Create an Input File',['../UsingMoris.html#InputFileSteps',1,'']]],
  ['input_20file_20with_20catch_34',['Include Input file with CATCH',['../group__EXA__DEV__GUIDE.html#autotoc_md5',1,'']]],
  ['input_20files_35',['Compiling and Running Input Files',['../UsingMoris.html#InputFileCompileRun',1,'']]],
  ['install_20moris_36',['How to &quot;install&quot; MORIS?',['../GettingStarted.html#GettingStartedInstallation',1,'']]],
  ['installation_37',['Installation',['../Bugzilla.html#BugzInstall',1,'']]],
  ['installation_20section_38',['Installation Section',['../ExplainCMakeLists.html#ExplainInstallSec',1,'']]],
  ['installation_20sections_39',['Config File and Installation Sections',['../group__AddingProjects.html#ConfigInstallSec',1,'']]],
  ['installation_20setup_20and_20procedures_40',['Bugzilla Installation, Setup, and Procedures',['../Bugzilla.html',1,'']]],
  ['installed_41',['Make Sure Git is Installed',['../BuildingMoris.html#GitCheck',1,'']]],
  ['installing_20doxygen_42',['Installing Doxygen',['../GettingStarted.html#InstallDoxy',1,'']]],
  ['installing_20the_20svn_20plug_20in_43',['Installing the SVN Plug-In',['../SVNTopics.html#SVNInstall',1,'']]],
  ['integrand_20of_20quantity_20of_20interest_20iqi_44',['Integrand of Quantity of Interest (IQI)',['../group__FE__IQI.html',1,'']]],
  ['integrand_20of_20weak_20form_20of_20governing_20equations_20iwg_45',['Integrand of Weak Form of Governing Equations (IWG)',['../group__FE__IWG.html',1,'']]],
  ['integration_20mesh_46',['integration mesh',['../group__XTKDecomp.html#XTK_Decomp_ElevateOrder_CollectConnectivity',1,'Collecting Connectivity Information about Existing Integration Mesh'],['../group__XTKDecomp.html#XTK_Decomp_HierSub_CollectConnectivity',1,'Collecting Connectivity Information about Existing Integration Mesh'],['../group__XTKElevateOrder.html#Collect',1,'connectivity Information about Existing Integration Mesh']]],
  ['interest_20iqi_47',['Integrand of Quantity of Interest (IQI)',['../group__FE__IQI.html',1,'']]],
  ['interface_48',['interface',['../opt_framework_user.html#opt_interface_new',1,'Adding a New OPT Interface'],['../BuildingMoris.html#CMakeCurses',1,'CMake Curses Interface'],['../group__HMR__Background__Mesh.html#autotoc_md300',1,'Method: Minimum Mesh Interface'],['../group__HMR__Background__Mesh.html#autotoc_md299',1,'Method: Minimum Processor Interface'],['../group__HMR__MTK__Interface.html',1,'MTK Interface'],['../opt_framework_user.html#opt_interface_user_defined',1,'User-defined OPT Criteria Interface']]],
  ['interface_20condition_49',['interface condition',['../FE_SP_Follower_Weight_Interface.html',1,'Stabilization Parameter for Follower Weight in Interface condition'],['../FE_SP_Leader_Weight_Interface.html',1,'Stabilization Parameter for Leader Weight in Interface condition']]],
  ['interface_20condition_20via_20nitsche_20formulation_50',['Stabilization Parameter for Interface condition via Nitsche formulation',['../FE_SP_Nitsche_Interface.html',1,'']]],
  ['interface_20module_51',['Model-Solver Interface Module',['../group__MSIfc.html',1,'']]],
  ['interface_20tutorial_52',['Model Solver Interface Tutorial',['../group__MSITutorial.html',1,'']]],
  ['interfaces_53',['interfaces',['../group__MTK__Interfaces.html',1,'Interfaces'],['../opt_framework_user.html#opt_criteria_user',1,'OPT Criteria Interfaces']]],
  ['interoperability_20between_20hmr_20xtk_20and_20fem_54',['Draft: Interoperability between HMR, XTK and FEM',['../group__MTK__Interoperability.html',1,'']]],
  ['interpolation_5frule_55',['Interpolation_Rule',['../group__FE__Interpolation__Rule.html',1,'']]],
  ['intersection_56',['Questions on Intersection',['../group__GE__overview.html#Qs',1,'']]],
  ['intersection_20example_57',['Intersection Example',['../group__GE__overview.html#intEx',1,'']]],
  ['introduction_58',['introduction',['../BugReporting.html#BR_Intro',1,'Introduction'],['../group__CommOverview.html#CommIntro',1,'Introduction'],['../group__CommOverview.html#autotoc_md0',1,'Introduction'],['../SVNTopics.html#SVNTopic',1,'Introduction'],['../MakefileWrapper.html#MWIntro',1,'Introduction'],['../group__FE__Compressible__NS.html#autotoc_md253',1,'Introduction']]],
  ['introduction_20to_20tensor_20class_59',['Introduction to Tensor Class',['../group__TensorClass.html#TensorIntro',1,'']]],
  ['iqi_60',['iqi',['../group__FE__IQI.html',1,'Integrand of Quantity of Interest (IQI)'],['../group__FE__IQI__MAXDOF.html',1,'Max DOF IQI']]],
  ['iqi_20formulation_61',['IQI Formulation',['../group__FE__IQI__MAXDOF.html#autotoc_md292',1,'']]],
  ['iqi_20function_20parameters_62',['IQI Function Parameters',['../group__FE__IQI__MAXDOF.html#autotoc_md290',1,'']]],
  ['is_20installed_63',['Make Sure Git is Installed',['../BuildingMoris.html#GitCheck',1,'']]],
  ['isotropic_20diffusion_64',['Isotropic Diffusion',['../FE_CM_Diffusion.html#autotoc_md239',1,'']]],
  ['isotropic_20diffusion_20with_20phase_20change_65',['Isotropic Diffusion with Phase Change',['../FE_CM_Diffusion.html#autotoc_md240',1,'']]],
  ['issues_20in_20the_20code_66',['Known Issues in the Code',['../group__KnownIssues.html',1,'']]],
  ['iwg_67',['iwg',['../group__FE__Compressible__NS.html#autotoc_md276',1,'Advective Energy Flux Boundary IWG'],['../group__FE__Compressible__NS.html#autotoc_md275',1,'Advective Mass Flux Boundary IWG'],['../group__FE__IWG.html',1,'Integrand of Weak Form of Governing Equations (IWG)']]],
  ['iwgs_68',['iwgs',['../group__FE__Compressible__NS.html#autotoc_md269',1,'Boundary IWGs'],['../group__FE__Compressible__NS.html#autotoc_md274',1,'Boundary IWGs'],['../group__FE__Compressible__NS.html#autotoc_md263',1,'Bulk IWGs'],['../FE_CM_Diffusion.html#autotoc_md244',1,'IWGs']]],
  ['iwgs_20for_20enforcing_20boundary_20conditions_69',['IWGs for enforcing Boundary Conditions',['../group__FE__Compressible__NS.html#autotoc_md277',1,'']]]
];
