var searchData=
[
  ['f_24_20tilde_20s_20f_24_0',['Non-negativity for \f$ \tilde{S} \f$',['../group__FE__Equations__Spalart__Allmaras__Turbulence.html#Non_negativity',1,'']]],
  ['face_20oriented_20ghost_20stabilization_1',['face oriented ghost stabilization',['../group__XTKGhost.html',1,'Face Oriented Ghost Stabilization'],['../group__FE__Equations__Spalart__Allmaras__Turbulence.html#Ghost',1,'Face-oriented Ghost Stabilization']]],
  ['facet_2',['Determining who constructs a ghost facet',['../group__XTKGhost.html#XTKGhostRules',1,'']]],
  ['factory_3',['Factory',['../group__HMR__Factory.html',1,'']]],
  ['failed_20at_20this_20function_3a_4',['FEM_Model::example_function - Failed at this function:',['../group__ErrorsAsserts.html#Error_test001',1,'']]],
  ['faults_5',['Segmentation Faults',['../group__SegFaults.html',1,'']]],
  ['fe_5fcm_5ffluid_6',['FE_CM_Fluid',['../group__FE__CM__Fluid.html',1,'']]],
  ['features_20of_20examples_7',['Features of Examples',['../group__EXA__Module.html#FeaturesOfExamples',1,'']]],
  ['fem_8',['Draft: Interoperability between HMR, XTK and FEM',['../group__MTK__Interoperability.html',1,'']]],
  ['fem_5fmodel_3a_3acreate_5fstabilization_5fparameters_20unkown_20phase_20name_3a_9',['FEM_Model::create_stabilization_parameters - Unkown phase name:',['../group__ErrorsAsserts.html#Error_FEM_Model001',1,'']]],
  ['fem_5fmodel_3a_3aexample_5ffunction_20failed_20at_20this_20function_3a_10',['FEM_Model::example_function - Failed at this function:',['../group__ErrorsAsserts.html#Error_test001',1,'']]],
  ['fickian_20problem_20for_20demonstrating_20gradient_20galerkin_20least_20squares_20stabilization_11',['Fickian Problem for Demonstrating Gradient Galerkin Least Squares Stabilization',['../EXA_THERMAL_GGLS_DEMO.html',1,'']]],
  ['fickian_20problem_20for_20linear_20diffusion_12',['Fickian Problem for Linear Diffusion',['../EXA_THERMAL_FICKIAN_PROBLEM.html',1,'']]],
  ['field_13',['field',['../group__GE__overview.html#def',1,'Defining the Field'],['../FE_SP_Ghost_Field.html',1,'Stabilization Parameter for Ghost on Field']]],
  ['field_20and_20mapper_14',['Field and Mapper',['../group__MTK__Mapper.html',1,'']]],
  ['field_20example_15',['Field Example',['../group__GE__overview.html#fieldEx',1,'']]],
  ['field_20problem_16',['field problem',['../EXA_Structure_Linear_Beam_Temperature_Field.html',1,'Beam Temperature Field Problem.'],['../EXA_Structure_Linear_Zienkiewicz_Zhu_Elemental_Field.html',1,'Linear Zienkiewicz Zhu Elemental Field Problem']]],
  ['field_5finterpolator_17',['Field_Interpolator',['../group__FE__Field__Interpolator.html',1,'']]],
  ['file_18',['file',['../group__AddingProjects.html#Depends',1,'Dependency file'],['../UsingMoris.html#InputFileSteps',1,'Steps to Create an Input File']]],
  ['file_20and_20installation_20sections_19',['Config File and Installation Sections',['../group__AddingProjects.html#ConfigInstallSec',1,'']]],
  ['file_20breakdown_20',['Depends File Breakdown',['../ExplainUpperLevel.html#ExplainDepends',1,'']]],
  ['file_20conventions_21',['File Conventions',['../group__CodingStyle.html#Other',1,'']]],
  ['file_20to_20the_20build_22',['Adding a Source File to the Build',['../group__WritingFunctions.html#CMakeSource',1,'']]],
  ['file_20with_20catch_23',['Include Input file with CATCH',['../group__EXA__DEV__GUIDE.html#autotoc_md5',1,'']]],
  ['files_24',['files',['../UsingMoris.html#InputFileCompileRun',1,'Compiling and Running Input Files'],['../group__CodingStyle.html#FileNaming',1,'Files'],['../SVNTopics.html#SVNIgnore',1,'Ignoring Directories or Files'],['../SVNTopics.html#SVNUpdate',1,'Updating to Latest revision of Files']]],
  ['files_20in_20eclipse_25',['Directories and Moving Files in Eclipse',['../SVNTopics.html#MovingFiles',1,'']]],
  ['files_20section_26',['Config Files Section',['../ExplainCMakeLists.html#ExplainConfigSec',1,'']]],
  ['files_20to_20the_20repository_27',['Importing an Existing Directory of Files to the Repository',['../SVNTopics.html#SVNImport',1,'']]],
  ['finalization_20of_20petsc_28',['Finalization of Petsc',['../group__SpAlgPetsc.html#SpAlgPetscFin',1,'']]],
  ['finalization_20of_20trilinos_29',['Finalization of Trilinos',['../group__SpAlgTrilinos.html#SpAlgTrilinosFin',1,'']]],
  ['finite_20element_20model_30',['Finite Element Model',['../group__FE__Model.html',1,'']]],
  ['finite_20element_20module_31',['Finite Element Module',['../group__FE__Module.html',1,'']]],
  ['finite_20element_20solution_32',['finite element solution',['../EXA_Structure_Thermo_Elastic_MOPAR.html#autotoc_md188',1,'Finite Element Solution'],['../EXA_Structure_Linear_STK_XTK_HeatConduction.html#autotoc_md234',1,'Finite Element Solution'],['../EXA_Oscillator.html#autotoc_md26',1,'Finite Element Solution']]],
  ['first_20executable_33',['First Executable',['../group__AddingExecutables.html#FirstExecutable',1,'']]],
  ['first_20library_20to_20a_20package_34',['How to Add the First Library to a Package',['../group__AddingLibraries.html#FirstLibrary',1,'']]],
  ['first_20order_20derivatives_35',['First Order Derivatives',['../group__FE__Higher__Order__Derivatives.html#autotoc_md285',1,'']]],
  ['fletcher_20goldfarb_20shanno_20lbfgs_36',['Limited-Memory Broyden-Fletcher-Goldfarb-Shanno (LBFGS)',['../opt_lbfgs.html',1,'opt_module']]],
  ['flow_37',['flow',['../group__FE__Compressible__NS.html#autotoc_md279',1,'Mass Flux Neumann BC (Prescribe Mass in-/out-flow)'],['../group__FE__Compressible__NS.html#autotoc_md280',1,'Thermal Neumann BC (Prescribe Heat in-/out-flow)']]],
  ['flow_20about_20a_20sphere_202d_38',['flow about a sphere 2d',['../EXA_OPTIMIZATION_THERMAL_FLOW_ABOUT_SPHERE_2D.html',1,'Thermal Flow about a sphere 2D'],['../EXA_OPTIMIZATION_THERMAL_TURBULENT_FLOW_ABOUT_SPHERE_2D.html',1,'Thermal Turbulent Flow about a sphere 2D']]],
  ['flow_20about_20a_20sphere_203d_39',['Thermal Flow about a sphere 3D',['../EXA_OPTIMIZATION_THERMAL_FLOW_ABOUT_SPHERE_3D.html',1,'']]],
  ['flow_20static_40',['Couette Flow Static',['../EXA_Couette_Flow_Static.html',1,'']]],
  ['fluid_20constitutive_20model_41',['Fluid Constitutive Model',['../FE_CM_Fluid.html',1,'']]],
  ['fluid_20physics_42',['List of Examples and Benchmarks for Fluid Physics',['../group__EXA__FLUID.html',1,'']]],
  ['fluid_20turbulence_20constitutive_20model_43',['Fluid Turbulence Constitutive Model',['../FE_CM_Fluid_Turbulence.html',1,'']]],
  ['flux_44',['Implementation of Grad-Div-Flux',['../FE_CM_Diffusion.html#autotoc_md243',1,'']]],
  ['flux_20boundary_20iwg_45',['flux boundary iwg',['../group__FE__Compressible__NS.html#autotoc_md276',1,'Advective Energy Flux Boundary IWG'],['../group__FE__Compressible__NS.html#autotoc_md275',1,'Advective Mass Flux Boundary IWG']]],
  ['flux_20neumann_20bc_20prescribe_20mass_20in_20out_20flow_46',['Mass Flux Neumann BC (Prescribe Mass in-/out-flow)',['../group__FE__Compressible__NS.html#autotoc_md279',1,'']]],
  ['folder_47',['folder',['../GettingStarted.html#MTPLSCheckout',1,'Checkout the MTPLS Folder'],['../RSYNC.html',1,'Commiting to MTLPS Folder']]],
  ['folder_20structure_48',['Folder Structure',['../group__EXA__DEV__GUIDE.html#autotoc_md4',1,'']]],
  ['follower_20weight_20in_20interface_20condition_49',['Stabilization Parameter for Follower Weight in Interface condition',['../FE_SP_Follower_Weight_Interface.html',1,'']]],
  ['for_203rd_20order_20shape_20function_20derivatives_50',['Geometric Jacobians for 3rd Order Shape Function Derivatives',['../group__FE__Higher__Order__Derivatives.html#autotoc_md288',1,'']]],
  ['for_20cmake_51',['Makefile wrapper for CMake',['../MakefileWrapper.html#MakefileWrapperCMake',1,'']]],
  ['for_20command_20line_20tool_52',['Tutorial for command line tool',['../group__HMR__Command__Line.html',1,'']]],
  ['for_20convective_20ghost_53',['Stabilization Parameter for Convective Ghost',['../FE_SP_Convective_Ghost.html',1,'']]],
  ['for_20demonstrating_20gradient_20galerkin_20least_20squares_20stabilization_54',['Fickian Problem for Demonstrating Gradient Galerkin Least Squares Stabilization',['../EXA_THERMAL_GGLS_DEMO.html',1,'']]],
  ['for_20developers_55',['For Developers',['../group__DevGroup.html',1,'']]],
  ['for_20diffusion_20with_20phase_20change_56',['Stefan&apos;s Problem for Diffusion with Phase Change',['../EXA_THERMAL_STEFANS_PROBLEM.html',1,'']]],
  ['for_20dirichlet_20condition_20via_20nitsche_20formulation_57',['Stabilization Parameter for Dirichlet condition via Nitsche formulation',['../FE_SP_Dirichlet_Nitsche.html',1,'']]],
  ['for_20dirichlet_20on_20modified_20viscosity_20via_20nitsche_58',['Stabilization Parameter for Dirichlet on Modified Viscosity via Nitsche',['../FE_SP_Spalart_Allmaras_Dirichlet_Nitsche.html',1,'']]],
  ['for_20dirichlet_20on_20velocity_20via_20nitsche_59',['Stabilization Parameter for Dirichlet on Velocity via Nitsche',['../FE_SP_Velocity_Dirichlet_Nitsche.html',1,'']]],
  ['for_20enforcing_20boundary_20conditions_60',['IWGs for enforcing Boundary Conditions',['../group__FE__Compressible__NS.html#autotoc_md277',1,'']]],
  ['for_20f_24_20tilde_20s_20f_24_61',['Non-negativity for \f$ \tilde{S} \f$',['../group__FE__Equations__Spalart__Allmaras__Turbulence.html#Non_negativity',1,'']]],
  ['for_20fluid_20physics_62',['List of Examples and Benchmarks for Fluid Physics',['../group__EXA__FLUID.html',1,'']]],
  ['for_20follower_20weight_20in_20interface_20condition_63',['Stabilization Parameter for Follower Weight in Interface condition',['../FE_SP_Follower_Weight_Interface.html',1,'']]],
  ['for_20ghost_20on_20field_64',['Stabilization Parameter for Ghost on Field',['../FE_SP_Ghost_Field.html',1,'']]],
  ['for_20interface_20condition_20via_20nitsche_20formulation_65',['Stabilization Parameter for Interface condition via Nitsche formulation',['../FE_SP_Nitsche_Interface.html',1,'']]],
  ['for_20leader_20weight_20in_20interface_20condition_66',['Stabilization Parameter for Leader Weight in Interface condition',['../FE_SP_Leader_Weight_Interface.html',1,'']]],
  ['for_20linear_20diffusion_67',['Fickian Problem for Linear Diffusion',['../EXA_THERMAL_FICKIAN_PROBLEM.html',1,'']]],
  ['for_20physics_20models_68',['Equations for Physics Models',['../group__FE__Physics__Equations.html',1,'']]],
  ['for_20pressure_20ghost_69',['Stabilization Parameter for Pressure Ghost',['../FE_SP_Pressure_Ghost.html',1,'']]],
  ['for_20shape_20and_20topology_20optimization_70',['List of Examples and Benchmarks for Shape and Topology Optimization',['../group__EXA__OPTIMIZATION.html',1,'']]],
  ['for_20structural_20problems_71',['List of Examples and Benchmarks for Structural Problems',['../group__EXA__STRUCTURAL.html',1,'']]],
  ['for_20supg_20stabilization_20in_20incompressible_20navier_20stokes_72',['Stabilization Parameter for SUPG stabilization in Incompressible Navier-Stokes',['../FE_SP_Incompressible_NS.html',1,'']]],
  ['for_20thermal_20diffusion_20and_20advection_73',['List of Examples and Benchmarks for Thermal Diffusion and Advection',['../group__EXA__THERMAL.html',1,'']]],
  ['for_20time_20velocity_20ghost_74',['Stabilization Parameter for Time Velocity Ghost',['../FE_SP_Time_Velocity_Ghost.html',1,'']]],
  ['for_20viscous_20ghost_75',['Stabilization Parameter for Viscous Ghost',['../FE_SP_Viscous_Ghost.html',1,'']]],
  ['form_76',['Boundary Terms in the Weak Form',['../group__FE__Compressible__NS.html#autotoc_md270',1,'']]],
  ['form_20of_20governing_20equations_20iwg_77',['Integrand of Weak Form of Governing Equations (IWG)',['../group__FE__IWG.html',1,'']]],
  ['format_78',['format',['../group__SpAlgPetsc.html#SpAlgPetscForm',1,'Petsc Format'],['../group__SpAlgTrilinos.html#SpAlgTrilinosForm',1,'Trilinos Format']]],
  ['formats_79',['Other Accepted Environment Variable Formats',['../BuildingMoris.html#OtherAcceptedEnvVars',1,'']]],
  ['formulating_20an_20optimization_20problem_80',['Formulating an Optimization Problem',['../opt_background.html#opt_formulation',1,'']]],
  ['formulation_81',['formulation',['../group__FE__Equations__Spalart__Allmaras__Turbulence.html#Dirichlet_BC',1,'Dirichlet Boundary Conditions via Nitsche&apos;s Formulation'],['../group__FE__IQI__MAXDOF.html#autotoc_md292',1,'IQI Formulation'],['../FE_SP_Dirichlet_Nitsche.html',1,'Stabilization Parameter for Dirichlet condition via Nitsche formulation'],['../FE_SP_Nitsche_Interface.html',1,'Stabilization Parameter for Interface condition via Nitsche formulation']]],
  ['four_20cylinders_20static_82',['Channel with Four Cylinders Static',['../EXA_THERMAL_ADVECTION_CHANNEL_WITH_FOUR_CYLINDERS_STATIC.html',1,'']]],
  ['four_20cylinders_20static_20temperature_20only_83',['Channel with Four Cylinders Static Temperature only',['../EXA_Thermal_Diffusion_Channel_with_Four_Cylinders_Static_Temp_Only.html',1,'']]],
  ['four_20cylinders_20transient_84',['Channel with Four Cylinders Transient',['../EXA_THERMAL_ADVECTION_CHANNEL_WITH_FOUR_CYLINDERS_TRANSIENT.html',1,'']]],
  ['framework_20in_20moris_85',['Optimization Framework in MORIS',['../opt_framework_user.html',1,'opt_module']]],
  ['from_20moris_3a_3amat_20to_20epetra_5ffecrsmatrix_20and_20epetra_5fvector_86',['Assembly from moris::mat to Epetra_FECrsMatrix and Epetra_Vector',['../group__SpAlgTrilinos.html#SpAlgTrilinosAssembly',1,'']]],
  ['function_87',['How to Write a Function',['../group__WritingFunctions.html#WriteFunction',1,'']]],
  ['function_20derivatives_88',['function derivatives',['../group__FE__Higher__Order__Derivatives.html#autotoc_md288',1,'Geometric Jacobians for 3rd Order Shape Function Derivatives'],['../group__FE__Higher__Order__Derivatives.html',1,'Shape Function Derivatives']]],
  ['function_20derivatives_20with_20respect_20to_20physical_20coordinates_89',['Derivation of Shape Function Derivatives with Respect to Physical Coordinates',['../group__FE__Higher__Order__Derivatives.html#autotoc_md284',1,'']]],
  ['function_20parameters_90',['IQI Function Parameters',['../group__FE__IQI__MAXDOF.html#autotoc_md290',1,'']]],
  ['function_3a_91',['FEM_Model::example_function - Failed at this function:',['../group__ErrorsAsserts.html#Error_test001',1,'']]],
  ['functions_92',['functions',['../group__CodingStyle.html#DeclareFunctions',1,'Declaring Functions'],['../group__CodingStyle.html#CodingFunctions',1,'Functions'],['../group__CodingStyle.html#NamingFuncs',1,'Naming Functions'],['../group__TensorClass.html#TensorFuncs',1,'Tensor Product Functions'],['../group__TensorClass.html',1,'The Tensor class and Related Functions'],['../group__WritingFunctions.html',1,'Writing Functions']]],
  ['functions_20psfs_93',['Phase-State Functions (PSFs)',['../FE_CM_Diffusion.html#autotoc_md241',1,'']]]
];
