var searchData=
[
  ['of_20a_204th_20and_202nd_20order_20tensors_0',['Inner Product of a 4th and 2nd Order Tensors',['../group__TensorClass.html#TensorFuncs_prod42',1,'']]],
  ['of_20a_20bug_1',['Status of a bug',['../Bugzilla.html#BugzStatus',1,'']]],
  ['of_20a_20linear_20system_20matrix_2',['Initialization of a Linear System Matrix',['../group__SpAlgPetsc.html#SpAlgPetscAllocMat',1,'']]],
  ['of_20a_20thermoelastic_20circle_20problem_3',['Shape Sensitivity of a Thermoelastic Circle Problem',['../EXA_OPTIMIZATION_SHAPE_SENS_CIRCLE_SWEEP_THERMOELASTIC.html',1,'']]],
  ['of_20a_20thermoelastic_20two_20material_20problem_4',['Shape Sensitivity of a Thermoelastic Two Material Problem',['../EXA_OPTIMIZATION_SHAPE_SENS_TWO_MAT_SWEEP_THERMOELASTIC.html',1,'']]],
  ['of_20a_20transient_20circle_20problem_5',['Shape Sensitivity of a Transient Circle Problem',['../EXA_OPTIMIZATION_SHAPE_SENS_CIRCLE_SWEEP_TRANSIENT.html',1,'']]],
  ['of_20a_20transient_20thermoelastic_20circle_20problem_6',['Shape Sensitivity of a Transient Thermoelastic Circle Problem',['../EXA_OPTIMIZATION_SHAPE_SENS_CIRCLE_SWEEP_THERMOELASTIC_TRANSIENT.html',1,'']]],
  ['of_20bugs_7',['Reporting of Bugs',['../BugReporting.html',1,'MiscTopics']]],
  ['of_20examples_8',['of examples',['../group__EXA__DEV__GUIDE.html#autotoc_md7',1,'Documentation of Examples'],['../group__EXA__Module.html#FeaturesOfExamples',1,'Features of Examples']]],
  ['of_20examples_20and_20benchmarks_20for_20fluid_20physics_9',['List of Examples and Benchmarks for Fluid Physics',['../group__EXA__FLUID.html',1,'']]],
  ['of_20examples_20and_20benchmarks_20for_20shape_20and_20topology_20optimization_10',['List of Examples and Benchmarks for Shape and Topology Optimization',['../group__EXA__OPTIMIZATION.html',1,'']]],
  ['of_20examples_20and_20benchmarks_20for_20structural_20problems_11',['List of Examples and Benchmarks for Structural Problems',['../group__EXA__STRUCTURAL.html',1,'']]],
  ['of_20examples_20and_20benchmarks_20for_20thermal_20diffusion_20and_20advection_12',['List of Examples and Benchmarks for Thermal Diffusion and Advection',['../group__EXA__THERMAL.html',1,'']]],
  ['of_20files_13',['Updating to Latest revision of Files',['../SVNTopics.html#SVNUpdate',1,'']]],
  ['of_20files_20to_20the_20repository_14',['Importing an Existing Directory of Files to the Repository',['../SVNTopics.html#SVNImport',1,'']]],
  ['of_20grad_20div_20flux_15',['Implementation of Grad-Div-Flux',['../FE_CM_Diffusion.html#autotoc_md243',1,'']]],
  ['of_20maps_16',['Naming of Maps',['../group__CodingStyle.html#MapsNmaing',1,'']]],
  ['of_20moris_20environment_20variables_17',['List of MORIS Environment Variables',['../BuildingMoris.html#EnvVarList',1,'']]],
  ['of_20moving_20asymptotes_20gcmma_18',['Globally Convergent Method of Moving Asymptotes (GCMMA)',['../opt_gcmma.html',1,'opt_module']]],
  ['of_20new_20cells_20and_20commiting_20them_20to_20the_20mesh_19',['of new Cells and commiting them to the Mesh',['../group__XTKElevateOrder.html#Creation',1,'']]],
  ['of_20petsc_20',['of petsc',['../group__SpAlgPetsc.html#SpAlgPetscFin',1,'Finalization of Petsc'],['../group__SpAlgPetsc.html#SpAlgPetscInit',1,'Initialization of Petsc']]],
  ['of_20petsc_20solver_21',['Outline of Petsc Solver',['../group__SpAlgPetsc.html',1,'']]],
  ['of_20quantity_20of_20interest_20iqi_22',['Integrand of Quantity of Interest (IQI)',['../group__FE__IQI.html',1,'']]],
  ['of_20shape_20function_20derivatives_20with_20respect_20to_20physical_20coordinates_23',['Derivation of Shape Function Derivatives with Respect to Physical Coordinates',['../group__FE__Higher__Order__Derivatives.html#autotoc_md284',1,'']]],
  ['of_20solution_20and_20rhs_20vectors_24',['Initialization of Solution and RHS Vectors',['../group__SpAlgPetsc.html#SpAlgPetscAllocVec',1,'']]],
  ['of_20source_20build_25',['Out-of-source build',['../MakefileWrapper.html#OutOfSourceBuild',1,'']]],
  ['of_20trilinos_26',['of trilinos',['../group__SpAlgTrilinos.html#SpAlgTrilinosFin',1,'Finalization of Trilinos'],['../group__SpAlgTrilinos.html#SpAlgTrilinosInit',1,'Initialization of Trilinos']]],
  ['of_20trilinos_20solver_27',['Outline of Trilinos Solver',['../group__SpAlgTrilinos.html',1,'']]],
  ['of_20weak_20form_20of_20governing_20equations_20iwg_28',['Integrand of Weak Form of Governing Equations (IWG)',['../group__FE__IWG.html',1,'']]],
  ['on_20field_29',['Stabilization Parameter for Ghost on Field',['../FE_SP_Ghost_Field.html',1,'']]],
  ['on_20how_20to_20set_20up_20examples_30',['Guide on how to set up examples',['../group__EXA__DEV__GUIDE.html',1,'']]],
  ['on_20intersection_31',['Questions on Intersection',['../group__GE__overview.html#Qs',1,'']]],
  ['on_20modified_20viscosity_20via_20nitsche_32',['Stabilization Parameter for Dirichlet on Modified Viscosity via Nitsche',['../FE_SP_Spalart_Allmaras_Dirichlet_Nitsche.html',1,'']]],
  ['on_20the_20command_20line_33',['Define Options on the Command Line',['../BuildingMoris.html#TerminalOptions',1,'']]],
  ['on_20velocity_20via_20nitsche_34',['Stabilization Parameter for Dirichlet on Velocity via Nitsche',['../FE_SP_Velocity_Dirichlet_Nitsche.html',1,'']]],
  ['one_20element_20material_20geometry_20pdv_20problem_35',['One Element Material Geometry PDV Problem',['../EXA_OPTIMIZATION_ONE_ELEMENT_MAT_GEO_PDV.html',1,'']]],
  ['only_36',['Channel with Four Cylinders Static Temperature only',['../EXA_Thermal_Diffusion_Channel_with_Four_Cylinders_Static_Temp_Only.html',1,'']]],
  ['operator_20alignment_37',['Operator Alignment',['../group__CodingStyle.html#OpAlignment',1,'']]],
  ['operator_20spacing_38',['Operator Spacing',['../group__CodingStyle.html#OpSpasing',1,'']]],
  ['opt_20algorithm_39',['OPT Algorithm',['../opt_algorithm_developer.html',1,'opt_module']]],
  ['opt_20algorithms_40',['OPT Algorithms',['../opt_framework_user.html#opt_algorithm_user',1,'']]],
  ['opt_20criteria_20interface_41',['User-defined OPT Criteria Interface',['../opt_framework_user.html#opt_interface_user_defined',1,'']]],
  ['opt_20criteria_20interfaces_42',['OPT Criteria Interfaces',['../opt_framework_user.html#opt_criteria_user',1,'']]],
  ['opt_20interface_43',['Adding a New OPT Interface',['../opt_framework_user.html#opt_interface_new',1,'']]],
  ['opt_20overview_44',['OPT Overview',['../opt_framework_user.html#opt_overview_user',1,'']]],
  ['opt_20problem_45',['opt problem',['../opt_framework_user.html#opt_problem_new',1,'Adding a New OPT Problem'],['../opt_framework_user.html#opt_problem_user',1,'OPT Problem'],['../opt_framework_user.html#opt_problem_user_defined',1,'User-defined OPT Problem']]],
  ['optimization_46',['List of Examples and Benchmarks for Shape and Topology Optimization',['../group__EXA__OPTIMIZATION.html',1,'']]],
  ['optimization_20background_47',['Optimization Background',['../opt_background.html',1,'opt_module']]],
  ['optimization_20framework_20in_20moris_48',['Optimization Framework in MORIS',['../opt_framework_user.html',1,'opt_module']]],
  ['optimization_20module_49',['Optimization Module',['../opt_module.html',1,'']]],
  ['optimization_20problem_50',['Formulating an Optimization Problem',['../opt_background.html#opt_formulation',1,'']]],
  ['optimization_20solutions_51',['Changes to Improve Optimization Solutions',['../UsingMoris.html#ConvergenceTweaks',1,'']]],
  ['optimized_20out_20anodeindex_20acoordinates_52',['moris::ge::Scaled_Field::get_base_field_value(&lt;optimized out&gt;,aNodeIndex,aCoordinates)',['../group__SegFaults.html#SegFault_GEN001',1,'']]],
  ['optional_20environment_20variables_53',['Optional Environment Variables',['../BuildingMoris.html#OptionalEnvVars',1,'']]],
  ['options_54',['ccmake Options',['../GettingStarted.html#ccmakeOptions',1,'']]],
  ['options_20on_20the_20command_20line_55',['Define Options on the Command Line',['../BuildingMoris.html#TerminalOptions',1,'']]],
  ['or_20files_56',['Ignoring Directories or Files',['../SVNTopics.html#SVNIgnore',1,'']]],
  ['order_57',['Elevate Order',['../group__XTKElevateOrder.html',1,'']]],
  ['order_20algorithm_58',['Elevate Order Algorithm',['../group__XTKDecomp.html#XTK_Decomp_ElevateOrder',1,'']]],
  ['order_20derivatives_59',['order derivatives',['../group__FE__Higher__Order__Derivatives.html#autotoc_md285',1,'First Order Derivatives'],['../group__FE__Higher__Order__Derivatives.html#autotoc_md286',1,'Higher Order Derivatives'],['../group__FE__Higher__Order__Derivatives.html#autotoc_md287',1,'Third Order Derivatives']]],
  ['order_20problem_60',['Thermoelastic Varying Order Problem.',['../EXA_Structure_Linear_Thermoelastic_Varying_Order.html',1,'']]],
  ['order_20shape_20function_20derivatives_61',['Geometric Jacobians for 3rd Order Shape Function Derivatives',['../group__FE__Higher__Order__Derivatives.html#autotoc_md288',1,'']]],
  ['order_20tensors_62',['Inner Product of a 4th and 2nd Order Tensors',['../group__TensorClass.html#TensorFuncs_prod42',1,'']]],
  ['organizing_20classes_63',['Organizing Classes',['../group__CodingStyle.html#OrgClasses',1,'']]],
  ['oriented_20ghost_20stabilization_64',['oriented ghost stabilization',['../group__XTKGhost.html',1,'Face Oriented Ghost Stabilization'],['../group__FE__Equations__Spalart__Allmaras__Turbulence.html#Ghost',1,'Face-oriented Ghost Stabilization']]],
  ['oscillator_65',['Oscillator',['../EXA_Oscillator.html',1,'']]],
  ['other_20accepted_20environment_20variable_20formats_66',['Other Accepted Environment Variable Formats',['../BuildingMoris.html#OtherAcceptedEnvVars',1,'']]],
  ['other_20conventions_67',['Other Conventions',['../group__CodingStyle.html#CodingMisc',1,'']]],
  ['out_20anodeindex_20acoordinates_68',['moris::ge::Scaled_Field::get_base_field_value(&lt;optimized out&gt;,aNodeIndex,aCoordinates)',['../group__SegFaults.html#SegFault_GEN001',1,'']]],
  ['out_20flow_69',['out flow',['../group__FE__Compressible__NS.html#autotoc_md279',1,'Mass Flux Neumann BC (Prescribe Mass in-/out-flow)'],['../group__FE__Compressible__NS.html#autotoc_md280',1,'Thermal Neumann BC (Prescribe Heat in-/out-flow)']]],
  ['out_20of_20source_20build_70',['Out-of-source build',['../MakefileWrapper.html#OutOfSourceBuild',1,'']]],
  ['outline_20of_20petsc_20solver_71',['Outline of Petsc Solver',['../group__SpAlgPetsc.html',1,'']]],
  ['outline_20of_20trilinos_20solver_72',['Outline of Trilinos Solver',['../group__SpAlgTrilinos.html',1,'']]],
  ['output_73',['Output',['../group__XTKOutput.html',1,'']]],
  ['overview_74',['overview',['../group__CommOverview.html',1,'Communicator Overview'],['../opt_framework_user.html#opt_overview_user',1,'OPT Overview'],['../group__XTKOverview.html',1,'Overview'],['../group__XTKDecomp.html#XTK_Decomp_Overview',1,'Overview'],['../group__MTK__Overview.html',1,'Overview'],['../group__GE__overview.html',1,'Overview']]]
];
