name: Generate and Deploy Doxygen Docs (CMake)

on:
  push:
    branches: [ main, docu ]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Doxygen and graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Generate Doxygen docs via CMake target
        run: cmake --build build --target doxy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/share/doc/html
          publish_branch: gh-pages
