var searchData=
[
  ['eclipse_0',['eclipse',['../GettingStarted.html#EclipseCheckout',1,'Checkout Using Eclipse'],['../SVNTopics.html#MovingFiles',1,'Directories and Moving Files in Eclipse'],['../group__EclipseSVNCommands.html',1,'SVN Commands in Eclipse']]],
  ['edge_20problem_1',['Mach Leading Edge Problem',['../EXA_OPTIMIZATION_MACH_LEADING_EDGE.html',1,'']]],
  ['edits_2',['Upper-Level Edits',['../group__AddingProjects.html#UpperLevel',1,'']]],
  ['elastic_20problem_3',['Single element coupled thermo-elastic problem',['../EXA_STRUCTURE_SINGLE_ELEMENT.html',1,'']]],
  ['element_4',['element',['../group__HMR__Background__Mesh.html#autotoc_md295',1,'Background Element'],['../group__FE__Element.html',1,'Element']]],
  ['element_20coupled_20thermo_20elastic_20problem_5',['Single element coupled thermo-elastic problem',['../EXA_STRUCTURE_SINGLE_ELEMENT.html',1,'']]],
  ['element_20material_20geometry_20pdv_20problem_6',['One Element Material Geometry PDV Problem',['../EXA_OPTIMIZATION_ONE_ELEMENT_MAT_GEO_PDV.html',1,'']]],
  ['element_20model_7',['Finite Element Model',['../group__FE__Model.html',1,'']]],
  ['element_20module_8',['Finite Element Module',['../group__FE__Module.html',1,'']]],
  ['element_20solution_9',['element solution',['../EXA_Structure_Linear_STK_XTK_HeatConduction.html#autotoc_md234',1,'Finite Element Solution'],['../EXA_Structure_Thermo_Elastic_MOPAR.html#autotoc_md188',1,'Finite Element Solution'],['../EXA_Oscillator.html#autotoc_md26',1,'Finite Element Solution']]],
  ['element_5fbis_10',['Element_Bis',['../group__FE__Element__Bis.html',1,'']]],
  ['elemental_20field_20problem_11',['Linear Zienkiewicz Zhu Elemental Field Problem',['../EXA_Structure_Linear_Zienkiewicz_Zhu_Elemental_Field.html',1,'']]],
  ['elevate_20order_12',['Elevate Order',['../group__XTKElevateOrder.html',1,'']]],
  ['elevate_20order_20algorithm_13',['Elevate Order Algorithm',['../group__XTKDecomp.html#XTK_Decomp_ElevateOrder',1,'']]],
  ['else_20statements_14',['If Else Statements',['../group__CodingStyle.html#IfElseStatements',1,'']]],
  ['energy_20conservation_15',['Energy Conservation',['../group__FE__Compressible__NS.html#autotoc_md273',1,'']]],
  ['energy_20equation_16',['Energy Equation',['../group__FE__Compressible__NS.html#autotoc_md266',1,'']]],
  ['energy_20flux_20boundary_20iwg_17',['Advective Energy Flux Boundary IWG',['../group__FE__Compressible__NS.html#autotoc_md276',1,'']]],
  ['enforcing_20boundary_20conditions_18',['IWGs for enforcing Boundary Conditions',['../group__FE__Compressible__NS.html#autotoc_md277',1,'']]],
  ['engine_19',['Geometry and Geometry Engine',['../group__XTKOverview.html#XTKGeometry',1,'']]],
  ['engine_20module_20',['Geometry Engine Module',['../group__GeomEng.html',1,'']]],
  ['enrichment_21',['Enrichment',['../group__XTKDictionary.html#XTK_Dict_Enrichment',1,'']]],
  ['enrichment_20strategy_22',['Enrichment Strategy',['../group__XTKEnrich.html',1,'']]],
  ['entities_23',['Mesh-Entities',['../group__XTKDictionary.html#XTK_Mesh_Entities',1,'']]],
  ['entity_20hierarchy_24',['Entity Hierarchy',['../group__XTKDictionary.html#XTK_Entity_Hierarchy',1,'']]],
  ['enums_25',['Enums',['../group__MTK__Enums.html',1,'']]],
  ['environment_20variable_20formats_26',['Other Accepted Environment Variable Formats',['../BuildingMoris.html#OtherAcceptedEnvVars',1,'']]],
  ['environment_20variables_27',['environment variables',['../BuildingMoris.html#EnvironmentVariables',1,'Environment Variables'],['../BuildingMoris.html#AddEnvVars',1,'How to Add Environment Variables'],['../BuildingMoris.html#EnvVarList',1,'List of MORIS Environment Variables'],['../BuildingMoris.html#OptionalEnvVars',1,'Optional Environment Variables'],['../BuildingMoris.html#RequiredEnvVars',1,'Required Environment Variables']]],
  ['epetra_5ffecrsmatrix_20and_20epetra_5fvector_28',['Assembly from moris::mat to Epetra_FECrsMatrix and Epetra_Vector',['../group__SpAlgTrilinos.html#SpAlgTrilinosAssembly',1,'']]],
  ['epetra_5fvector_29',['Assembly from moris::mat to Epetra_FECrsMatrix and Epetra_Vector',['../group__SpAlgTrilinos.html#SpAlgTrilinosAssembly',1,'']]],
  ['eqnmgr_30',['EqnMgr',['../group__EqnMgr.html',1,'']]],
  ['eqnobj_31',['EqnObj',['../group__EqnObj.html',1,'']]],
  ['equation_32',['equation',['../group__FE__Compressible__NS.html#autotoc_md266',1,'Energy Equation'],['../group__FE__Compressible__NS.html#autotoc_md265',1,'Momentum Equation']]],
  ['equations_33',['equations',['../group__FE__Compressible__NS.html',1,'Compressible Navier-Stokes Equations.'],['../group__FE__Equations__Diffusion__Advection__Reaction.html',1,'Diffusion-Advection-Reaction Equations'],['../group__FE__Compressible__NS.html#autotoc_md255',1,'Governing Equations'],['../FE_CM_Diffusion.html#autotoc_md237',1,'Governing Equations'],['../group__FE__Equations__Incompressible__Navier__Stokes.html',1,'Incompressible Navier-Stokes Equations'],['../group__FE__Equations__Spalart__Allmaras__Turbulence.html',1,'Spalart-Allmaras Turbulence Model Equations']]],
  ['equations_20for_20physics_20models_34',['Equations for Physics Models',['../group__FE__Physics__Equations.html',1,'']]],
  ['equations_20iwg_35',['Integrand of Weak Form of Governing Equations (IWG)',['../group__FE__IWG.html',1,'']]],
  ['errors_36',['Toubleshooting Errors',['../group__TroubleshootingGroup.html',1,'']]],
  ['errors_20and_20asserts_37',['Errors and Asserts',['../group__ErrorsAsserts.html',1,'']]],
  ['evironmental_20variable_38',['Setting MORISROOT as an Evironmental Variable',['../GettingStarted.html#EnvVar',1,'']]],
  ['example_39',['example',['../group__XTKEnrich.html#EnrExample',1,'Conceptual Example'],['../group__EXA__DEV__GUIDE.html#autotoc_md3',1,'Creating an example'],['../group__GE__overview.html#fieldEx',1,'Field Example'],['../group__GE__overview.html#intEx',1,'Intersection Example']]],
  ['examples_40',['examples',['../FE_CM_Diffusion.html#autotoc_md251',1,'Benchmarks/Examples'],['../group__EXA__DEV__GUIDE.html#autotoc_md7',1,'Documentation of Examples'],['../group__EXA__Module.html#FeaturesOfExamples',1,'Features of Examples'],['../group__EXA__DEV__GUIDE.html',1,'Guide on how to set up examples']]],
  ['examples_20and_20benchmarks_41',['Examples and Benchmarks',['../group__EXA__Module.html',1,'']]],
  ['examples_20and_20benchmarks_20for_20fluid_20physics_42',['List of Examples and Benchmarks for Fluid Physics',['../group__EXA__FLUID.html',1,'']]],
  ['examples_20and_20benchmarks_20for_20shape_20and_20topology_20optimization_43',['List of Examples and Benchmarks for Shape and Topology Optimization',['../group__EXA__OPTIMIZATION.html',1,'']]],
  ['examples_20and_20benchmarks_20for_20structural_20problems_44',['List of Examples and Benchmarks for Structural Problems',['../group__EXA__STRUCTURAL.html',1,'']]],
  ['examples_20and_20benchmarks_20for_20thermal_20diffusion_20and_20advection_45',['List of Examples and Benchmarks for Thermal Diffusion and Advection',['../group__EXA__THERMAL.html',1,'']]],
  ['executable_46',['executable',['../group__WritingFunctions.html#ExecutableSource',1,'Add to an Executable'],['../group__AddingExecutables.html#FirstExecutable',1,'First Executable']]],
  ['executable_20sections_47',['Library and Executable sections',['../group__AddingProjects.html#LibraryExecutableSec',1,'']]],
  ['executables_48',['executables',['../group__AddingExecutables.html',1,'Adding Executables'],['../group__AddingExecutables.html#AdditonalExecutable',1,'Additional Executables']]],
  ['existing_20directory_20of_20files_20to_20the_20repository_49',['Importing an Existing Directory of Files to the Repository',['../SVNTopics.html#SVNImport',1,'']]],
  ['existing_20integration_20mesh_50',['existing integration mesh',['../group__XTKDecomp.html#XTK_Decomp_HierSub_CollectConnectivity',1,'Collecting Connectivity Information about Existing Integration Mesh'],['../group__XTKDecomp.html#XTK_Decomp_ElevateOrder_CollectConnectivity',1,'Collecting Connectivity Information about Existing Integration Mesh'],['../group__XTKElevateOrder.html#Collect',1,'connectivity Information about Existing Integration Mesh']]],
  ['explainconfig_51',['ExplainConfig',['../ExplainConfig.html',1,'']]]
];
