var searchData=
[
  ['calculation_20class_0',['T-Matrix Calculation Class',['../group__HMR__TMatrix.html',1,'']]],
  ['catch_1',['Include Input file with CATCH',['../group__EXA__DEV__GUIDE.html#autotoc_md5',1,'']]],
  ['ccmake_20options_2',['ccmake Options',['../GettingStarted.html#ccmakeOptions',1,'']]],
  ['cell_20groups_3',['IG-Cell Groups',['../group__XTKDictionary.html#XTK_Mesh_IG-Cell_Group',1,'']]],
  ['cells_4',['Necessary Information about new Cells',['../group__XTKElevateOrder.html#Computing',1,'']]],
  ['cells_20and_20commiting_20them_20to_20the_20mesh_5',['of new Cells and commiting them to the Mesh',['../group__XTKElevateOrder.html#Creation',1,'']]],
  ['change_6',['change',['../FE_CM_Diffusion.html#autotoc_md240',1,'Isotropic Diffusion with Phase Change'],['../EXA_THERMAL_STEFANS_PROBLEM.html',1,'Stefan&apos;s Problem for Diffusion with Phase Change']]],
  ['changes_7',['Committing Changes',['../SVNTopics.html#SVNCommit',1,'']]],
  ['changes_20to_20improve_20optimization_20solutions_8',['Changes to Improve Optimization Solutions',['../UsingMoris.html#ConvergenceTweaks',1,'']]],
  ['channel_202d_20static_9',['Channel 2D Static',['../EXA_Channel_2D_Static.html',1,'']]],
  ['channel_20with_20four_20cylinders_20static_10',['Channel with Four Cylinders Static',['../EXA_THERMAL_ADVECTION_CHANNEL_WITH_FOUR_CYLINDERS_STATIC.html',1,'']]],
  ['channel_20with_20four_20cylinders_20static_20temperature_20only_11',['Channel with Four Cylinders Static Temperature only',['../EXA_Thermal_Diffusion_Channel_with_Four_Cylinders_Static_Temp_Only.html',1,'']]],
  ['channel_20with_20four_20cylinders_20transient_12',['Channel with Four Cylinders Transient',['../EXA_THERMAL_ADVECTION_CHANNEL_WITH_FOUR_CYLINDERS_TRANSIENT.html',1,'']]],
  ['channels_20with_20separation_20wall_20transient_13',['Two Channels with Separation Wall Transient',['../EXA_THERMAL_ADVECTION_TWO_CHANNELS.html',1,'']]],
  ['checkout_20moris_14',['Checkout MORIS',['../GettingStarted.html#Checkout',1,'']]],
  ['checkout_20the_20mtpls_20folder_15',['Checkout the MTPLS Folder',['../GettingStarted.html#MTPLSCheckout',1,'']]],
  ['checkout_20using_20eclipse_16',['Checkout Using Eclipse',['../GettingStarted.html#EclipseCheckout',1,'']]],
  ['checkout_20using_20the_20terminal_17',['Checkout Using the Terminal',['../GettingStarted.html#CommandCheckout',1,'']]],
  ['checkout_20with_20git_18',['Checkout with Git',['../BuildingMoris.html#GitCommandCheckout',1,'']]],
  ['checks_19',['Creating Checks',['../group__EXA__DEV__GUIDE.html#autotoc_md6',1,'']]],
  ['checks_20in_20the_20code_20',['Checks in the code',['../group__CodingStyle.html#Checks',1,'']]],
  ['child_20mesh_21',['Child Mesh',['../group__XTKDictionary.html#XTK_Mesh_Child_Mesh',1,'']]],
  ['circle_20problem_22',['circle problem',['../EXA_OPTIMIZATION_SHAPE_SENS_CIRCLE_SWEEP_THERMOELASTIC.html',1,'Shape Sensitivity of a Thermoelastic Circle Problem'],['../EXA_OPTIMIZATION_SHAPE_SENS_CIRCLE_SWEEP_TRANSIENT.html',1,'Shape Sensitivity of a Transient Circle Problem'],['../EXA_OPTIMIZATION_SHAPE_SENS_CIRCLE_SWEEP_THERMOELASTIC_TRANSIENT.html',1,'Shape Sensitivity of a Transient Thermoelastic Circle Problem']]],
  ['circle_20sweep_23',['circle sweep',['../EXA_Shape_Sensitivity_Bspline.html',1,'Shape Sensitivity Circle Sweep'],['../EXA_Shape_Sensitivity_Sweep.html',1,'Shape Sensitivity Circle Sweep']]],
  ['class_24',['class',['../group__HMR__Main__Class.html',1,'HMR Main Class'],['../group__TensorClass.html#TensorIntro',1,'Introduction to Tensor Class'],['../group__HMR__Base__Mesh.html',1,'Mesh Base Class'],['../group__HMR__TMatrix.html',1,'T-Matrix Calculation Class']]],
  ['class_20and_20related_20functions_25',['The Tensor class and Related Functions',['../group__TensorClass.html',1,'']]],
  ['classes_26',['classes',['../group__CodingStyle.html#CodingClasses',1,'Classes'],['../group__GE__classes.html',1,'Classes'],['../group__MTK__Classes.html',1,'Classes'],['../group__CodingStyle.html#NamingClasses',1,'Naming Classes'],['../group__CodingStyle.html#OrgClasses',1,'Organizing Classes']]],
  ['cleaning_20doxygen_27',['Cleaning Doxygen',['../GettingStarted.html#CleanDoxy',1,'']]],
  ['cleanup_28',['Mesh Cleanup',['../group__XTKCleanup.html',1,'']]],
  ['cluster_29',['cluster',['../group__FE__Cluster.html',1,'Cluster'],['../group__XTKGhost.html#XTKGhostSpecialCluster',1,'Transition Double Side Cluster']]],
  ['cluster_20measure_20problem_30',['SA Cluster Measure Problem',['../EXA_OPTIMIZATION_SA_CLUSTER_MEASURE.html',1,'']]],
  ['cmake_31',['cmake',['../group__CMakeGroup.html',1,'CMake'],['../group__WritingTests.html#CMakeTest',1,'How to Add a Test in CMake'],['../MakefileWrapper.html#MakefileWrapperCMake',1,'Makefile wrapper for CMake']]],
  ['cmake_20curses_20interface_32',['CMake Curses Interface',['../BuildingMoris.html#CMakeCurses',1,'']]],
  ['cmakelists_33',['Project-Level CMakeLists',['../group__AddingProjects.html#CMakeLists',1,'']]],
  ['cmakelists_20details_34',['cmakelists details',['../ExplainCMakeLists.html',1,'Project-Level CMakeLists Details'],['../ExplainCMakeLists.html#ExplainProjectSrc',1,'Source-level CMakeLists Details'],['../ExplainCMakeLists.html#ExplainProjectTests',1,'Test-Level CMakeLists Details'],['../ExplainCMakeLists.html#ExplainTopLevelProject',1,'Top CMakeLists Details']]],
  ['cmakelists_20txt_35',['cmakelists txt',['../group__AddingProjects.html#TopLevelProject',1,'Project Top-Level CMakeLists.txt'],['../group__AddingProjects.html#ProjectSrc',1,'Source-Level CMakeLists.txt'],['../group__AddingProjects.html#ProjectTests',1,'Test-Level CMakeLists.txt'],['../group__AddingProjects.html#TopLevel',1,'Top-level CMakeLists.txt']]],
  ['code_36',['code',['../group__CodingStyle.html#Checks',1,'Checks in the code'],['../GettingStarted.html#CompilingCode',1,'Compile the Code'],['../group__KnownIssues.html',1,'Known Issues in the Code']]],
  ['code_20details_37',['code details',['../ExplainUpperLevel.html#ExplainTopLevel',1,'Top-Level Code Details'],['../ExplainUpperLevel.html',1,'Upper-Level Code Details'],['../ExplainUpperLevel.html#ExplainUtilities',1,'Utlilities Code Details']]],
  ['coding_20style_38',['Coding Style',['../group__CodingStyle.html',1,'']]],
  ['collecting_20connectivity_20information_20about_20existing_20integration_20mesh_39',['collecting connectivity information about existing integration mesh',['../group__XTKDecomp.html#XTK_Decomp_HierSub_CollectConnectivity',1,'Collecting Connectivity Information about Existing Integration Mesh'],['../group__XTKDecomp.html#XTK_Decomp_ElevateOrder_CollectConnectivity',1,'Collecting Connectivity Information about Existing Integration Mesh']]],
  ['command_20line_40',['Define Options on the Command Line',['../BuildingMoris.html#TerminalOptions',1,'']]],
  ['command_20line_20tool_41',['Tutorial for command line tool',['../group__HMR__Command__Line.html',1,'']]],
  ['commands_42',['commands',['../group__DocumentationStyle.html#DoxyCommands',1,'Related Doxygen Commands'],['../SomeUsefulCommands.html',1,'Some Useful Commands']]],
  ['commands_20in_20eclipse_43',['SVN Commands in Eclipse',['../group__EclipseSVNCommands.html',1,'']]],
  ['comments_44',['Repeated Comments',['../group__DocumentationStyle.html#RepatedDocs',1,'']]],
  ['commit_20messages_45',['Commit Messages',['../group__DocumentationStyle.html#CommitMessages',1,'']]],
  ['commiting_20them_20to_20the_20mesh_46',['of new Cells and commiting them to the Mesh',['../group__XTKElevateOrder.html#Creation',1,'']]],
  ['commiting_20to_20mtlps_20folder_47',['Commiting to MTLPS Folder',['../RSYNC.html',1,'MiscTopics']]],
  ['committing_48',['Before Committing',['../group__EclipseSVNCommands.html#CommitProcedure',1,'']]],
  ['committing_20changes_49',['Committing Changes',['../SVNTopics.html#SVNCommit',1,'']]],
  ['communication_20manager_50',['Communication Manager',['../group__CommOverview.html#autotoc_md1',1,'']]],
  ['communication_20module_51',['Communication Module',['../group__CommModule.html',1,'']]],
  ['communication_20tools_52',['Communication Tools',['../group__CommOverview.html#autotoc_md2',1,'']]],
  ['communicator_53',['Adding a Communicator',['../group__CommOverview.html#CommAdd',1,'']]],
  ['communicator_20overview_54',['Communicator Overview',['../group__CommOverview.html',1,'']]],
  ['comparing_20results_55',['Running a Sweep and Comparing Results',['../UsingMoris.html#InputFileSweep',1,'']]],
  ['compile_20the_20code_56',['Compile the Code',['../GettingStarted.html#CompilingCode',1,'']]],
  ['compiling_20and_20running_20input_20files_57',['Compiling and Running Input Files',['../UsingMoris.html#InputFileCompileRun',1,'']]],
  ['compiling_20documentation_58',['Compiling Documentation',['../BuildingMoris.html#BuildingDoxygen',1,'']]],
  ['compressible_20navier_20stokes_20equations_59',['Compressible Navier-Stokes Equations.',['../group__FE__Compressible__NS.html',1,'']]],
  ['computing_20necessary_20information_20about_20new_20vertices_60',['Computing Necessary Information about new Vertices',['../group__XTKDecomp.html#XTK_Decomp_ElevateOrder_VertInfo',1,'']]],
  ['concepts_61',['Phase Concepts',['../group__XTKConcepts.html',1,'']]],
  ['conceptual_20example_62',['Conceptual Example',['../group__XTKEnrich.html#EnrExample',1,'']]],
  ['condition_63',['condition',['../group__FE__Dirichlet__BCs.html',1,'Dirichlet Boundary Condition'],['../FE_SP_Follower_Weight_Interface.html',1,'Stabilization Parameter for Follower Weight in Interface condition'],['../FE_SP_Leader_Weight_Interface.html',1,'Stabilization Parameter for Leader Weight in Interface condition']]],
  ['condition_20via_20nitsche_20formulation_64',['condition via nitsche formulation',['../FE_SP_Dirichlet_Nitsche.html',1,'Stabilization Parameter for Dirichlet condition via Nitsche formulation'],['../FE_SP_Nitsche_Interface.html',1,'Stabilization Parameter for Interface condition via Nitsche formulation']]],
  ['conditions_65',['IWGs for enforcing Boundary Conditions',['../group__FE__Compressible__NS.html#autotoc_md277',1,'']]],
  ['conditions_20via_20nitsche_20s_20formulation_66',['Dirichlet Boundary Conditions via Nitsche&apos;s Formulation',['../group__FE__Equations__Spalart__Allmaras__Turbulence.html#Dirichlet_BC',1,'']]],
  ['config_20file_20and_20installation_20sections_67',['Config File and Installation Sections',['../group__AddingProjects.html#ConfigInstallSec',1,'']]],
  ['config_20files_20section_68',['Config Files Section',['../ExplainCMakeLists.html#ExplainConfigSec',1,'']]],
  ['configuration_69',['Building your MORIS Configuration',['../BuildingMoris.html#MorisBuild',1,'']]],
  ['configuring_20moris_70',['Configuring MORIS',['../BuildingMoris.html#ConfiguringMoris',1,'']]],
  ['connectivity_20information_20about_20existing_20integration_20mesh_71',['connectivity information about existing integration mesh',['../group__XTKDecomp.html#XTK_Decomp_HierSub_CollectConnectivity',1,'Collecting Connectivity Information about Existing Integration Mesh'],['../group__XTKDecomp.html#XTK_Decomp_ElevateOrder_CollectConnectivity',1,'Collecting Connectivity Information about Existing Integration Mesh'],['../group__XTKElevateOrder.html#Collect',1,'connectivity Information about Existing Integration Mesh']]],
  ['consecutive_20libraries_72',['How to Add Consecutive Libraries',['../group__AddingLibraries.html#ConsecutiveLibraries',1,'']]],
  ['conservation_73',['conservation',['../group__FE__Compressible__NS.html#autotoc_md273',1,'Energy Conservation'],['../group__FE__Compressible__NS.html#autotoc_md271',1,'Mass Conservation'],['../group__FE__Compressible__NS.html#autotoc_md264',1,'Mass Conservation'],['../group__FE__Compressible__NS.html#autotoc_md272',1,'Momentum Conservation']]],
  ['considerations_74',['considerations',['../group__XTKEnrich.html#EnrParallel',1,'Parallel Considerations'],['../group__XTKGhost.html#XTKGhostParallel',1,'Parallel Considerations'],['../group__XTKDictionary.html#XTK_Parallel-Considerations',1,'Parallel-Considerations']]],
  ['constitutive_20model_75',['constitutive model',['../FE_CM_Fluid.html',1,'Fluid Constitutive Model'],['../FE_CM_Fluid_Turbulence.html',1,'Fluid Turbulence Constitutive Model'],['../FE_CM_Diffusion.html',1,'Thermal Diffusion Constitutive Model']]],
  ['constitutive_20models_76',['constitutive models',['../FE_CM_Diffusion.html#autotoc_md238',1,'Constitutive Models'],['../group__FE__Compressible__NS.html#autotoc_md257',1,'Constitutive Models'],['../group__FE__CM.html',1,'Constitutive Models']]],
  ['constructs_20a_20ghost_20facet_77',['Determining who constructs a ghost facet',['../group__XTKGhost.html#XTKGhostRules',1,'']]],
  ['contact_20sensitivity_20problem_78',['Contact Sensitivity Problem',['../EXA_OPTIMIZATION_CONTACT_SENSITIVITY.html',1,'']]],
  ['convective_20ghost_79',['Stabilization Parameter for Convective Ghost',['../FE_SP_Convective_Ghost.html',1,'']]],
  ['conventions_80',['conventions',['../group__CodingStyle.html#Other',1,'File Conventions'],['../group__CodingStyle.html#CodingMisc',1,'Other Conventions']]],
  ['convergent_20method_20of_20moving_20asymptotes_20gcmma_81',['Globally Convergent Method of Moving Asymptotes (GCMMA)',['../opt_gcmma.html',1,'opt_module']]],
  ['coordinates_82',['Derivation of Shape Function Derivatives with Respect to Physical Coordinates',['../group__FE__Higher__Order__Derivatives.html#autotoc_md284',1,'']]],
  ['couette_20flow_20static_83',['Couette Flow Static',['../EXA_Couette_Flow_Static.html',1,'']]],
  ['coupled_20thermo_20elastic_20problem_84',['Single element coupled thermo-elastic problem',['../EXA_STRUCTURE_SINGLE_ELEMENT.html',1,'']]],
  ['create_20an_20input_20file_85',['Steps to Create an Input File',['../UsingMoris.html#InputFileSteps',1,'']]],
  ['creating_20an_20example_86',['Creating an example',['../group__EXA__DEV__GUIDE.html#autotoc_md3',1,'']]],
  ['creating_20checks_87',['Creating Checks',['../group__EXA__DEV__GUIDE.html#autotoc_md6',1,'']]],
  ['creating_20the_20repository_88',['Creating the Repository',['../SVNTopics.html#CreateRepo',1,'']]],
  ['criteria_20interface_89',['User-defined OPT Criteria Interface',['../opt_framework_user.html#opt_interface_user_defined',1,'']]],
  ['criteria_20interfaces_90',['OPT Criteria Interfaces',['../opt_framework_user.html#opt_criteria_user',1,'']]],
  ['curses_20interface_91',['CMake Curses Interface',['../BuildingMoris.html#CMakeCurses',1,'']]],
  ['cut_20bar_20static_20problem_92',['SA Cut Bar Static Problem',['../EXA_OPTIMIZATION_SA_CUT_BAR_STATIC.html',1,'']]],
  ['cut_20pcbar_20transient_20problem_93',['SA Cut PCBar Transient Problem',['../EXA_OPTIMIZATION_SA_CUT_PCBAR_TRANSIENT.html',1,'']]],
  ['cvs_20svn_20differences_94',['CVS - SVN Differences',['../SVNTopics.html#Differences',1,'']]],
  ['cylinder_20static_95',['Single Phase Hollow Cylinder Static',['../EXA_Single_Phase_Hollow_Cylinder_Static.html',1,'']]],
  ['cylinders_20static_96',['Channel with Four Cylinders Static',['../EXA_THERMAL_ADVECTION_CHANNEL_WITH_FOUR_CYLINDERS_STATIC.html',1,'']]],
  ['cylinders_20static_20temperature_20only_97',['Channel with Four Cylinders Static Temperature only',['../EXA_Thermal_Diffusion_Channel_with_Four_Cylinders_Static_Temp_Only.html',1,'']]],
  ['cylinders_20transient_98',['Channel with Four Cylinders Transient',['../EXA_THERMAL_ADVECTION_CHANNEL_WITH_FOUR_CYLINDERS_TRANSIENT.html',1,'']]]
];
