var searchData=
[
  ['s_20problem_20for_20diffusion_20with_20phase_20change_0',['Stefan&apos;s Problem for Diffusion with Phase Change',['../EXA_THERMAL_STEFANS_PROBLEM.html',1,'']]],
  ['sa_20cluster_20measure_20problem_1',['SA Cluster Measure Problem',['../EXA_OPTIMIZATION_SA_CLUSTER_MEASURE.html',1,'']]],
  ['sa_20cut_20bar_20static_20problem_2',['SA Cut Bar Static Problem',['../EXA_OPTIMIZATION_SA_CUT_BAR_STATIC.html',1,'']]],
  ['sa_20cut_20pcbar_20transient_20problem_3',['SA Cut PCBar Transient Problem',['../EXA_OPTIMIZATION_SA_CUT_PCBAR_TRANSIENT.html',1,'']]],
  ['seeding_4',['Levelset Beam SIMP Hole Seeding',['../EXA_OPTIMIZATION_SIMP_HOLE_SEEDING.html',1,'']]],
  ['sensitivity_20circle_20sweep_5',['sensitivity circle sweep',['../EXA_Shape_Sensitivity_Sweep.html',1,'Shape Sensitivity Circle Sweep'],['../EXA_Shape_Sensitivity_Bspline.html',1,'Shape Sensitivity Circle Sweep']]],
  ['sensitivity_20of_20a_20thermoelastic_20circle_20problem_6',['Shape Sensitivity of a Thermoelastic Circle Problem',['../EXA_OPTIMIZATION_SHAPE_SENS_CIRCLE_SWEEP_THERMOELASTIC.html',1,'']]],
  ['sensitivity_20of_20a_20thermoelastic_20two_20material_20problem_7',['Shape Sensitivity of a Thermoelastic Two Material Problem',['../EXA_OPTIMIZATION_SHAPE_SENS_TWO_MAT_SWEEP_THERMOELASTIC.html',1,'']]],
  ['sensitivity_20of_20a_20transient_20circle_20problem_8',['Shape Sensitivity of a Transient Circle Problem',['../EXA_OPTIMIZATION_SHAPE_SENS_CIRCLE_SWEEP_TRANSIENT.html',1,'']]],
  ['sensitivity_20of_20a_20transient_20thermoelastic_20circle_20problem_9',['Shape Sensitivity of a Transient Thermoelastic Circle Problem',['../EXA_OPTIMIZATION_SHAPE_SENS_CIRCLE_SWEEP_THERMOELASTIC_TRANSIENT.html',1,'']]],
  ['sensitivity_20problem_10',['sensitivity problem',['../EXA_OPTIMIZATION_BEDDDING_SENSITIVITY.html',1,'Bedding Sensitivity Problem'],['../EXA_OPTIMIZATION_CONTACT_SENSITIVITY.html',1,'Contact Sensitivity Problem']]],
  ['separation_20wall_20transient_11',['Two Channels with Separation Wall Transient',['../EXA_THERMAL_ADVECTION_TWO_CHANNELS.html',1,'']]],
  ['sequential_20quadratic_20programming_20sqp_12',['Sequential Quadratic Programming (SQP)',['../opt_sqp.html',1,'opt_module']]],
  ['setup_20and_20procedures_13',['Bugzilla Installation, Setup, and Procedures',['../Bugzilla.html',1,'']]],
  ['shanno_20lbfgs_14',['Limited-Memory Broyden-Fletcher-Goldfarb-Shanno (LBFGS)',['../opt_lbfgs.html',1,'opt_module']]],
  ['shape_20sensitivity_20circle_20sweep_15',['shape sensitivity circle sweep',['../EXA_Shape_Sensitivity_Bspline.html',1,'Shape Sensitivity Circle Sweep'],['../EXA_Shape_Sensitivity_Sweep.html',1,'Shape Sensitivity Circle Sweep']]],
  ['shape_20sensitivity_20of_20a_20thermoelastic_20circle_20problem_16',['Shape Sensitivity of a Thermoelastic Circle Problem',['../EXA_OPTIMIZATION_SHAPE_SENS_CIRCLE_SWEEP_THERMOELASTIC.html',1,'']]],
  ['shape_20sensitivity_20of_20a_20thermoelastic_20two_20material_20problem_17',['Shape Sensitivity of a Thermoelastic Two Material Problem',['../EXA_OPTIMIZATION_SHAPE_SENS_TWO_MAT_SWEEP_THERMOELASTIC.html',1,'']]],
  ['shape_20sensitivity_20of_20a_20transient_20circle_20problem_18',['Shape Sensitivity of a Transient Circle Problem',['../EXA_OPTIMIZATION_SHAPE_SENS_CIRCLE_SWEEP_TRANSIENT.html',1,'']]],
  ['shape_20sensitivity_20of_20a_20transient_20thermoelastic_20circle_20problem_19',['Shape Sensitivity of a Transient Thermoelastic Circle Problem',['../EXA_OPTIMIZATION_SHAPE_SENS_CIRCLE_SWEEP_THERMOELASTIC_TRANSIENT.html',1,'']]],
  ['simp_20',['SIMP',['../EXA_SIMP.html',1,'']]],
  ['simp_20hole_20seeding_21',['Levelset Beam SIMP Hole Seeding',['../EXA_OPTIMIZATION_SIMP_HOLE_SEEDING.html',1,'']]],
  ['single_20element_20coupled_20thermo_20elastic_20problem_22',['Single element coupled thermo-elastic problem',['../EXA_STRUCTURE_SINGLE_ELEMENT.html',1,'']]],
  ['single_20phase_20hollow_20cylinder_20static_23',['Single Phase Hollow Cylinder Static',['../EXA_Single_Phase_Hollow_Cylinder_Static.html',1,'']]],
  ['some_20useful_20commands_24',['Some Useful Commands',['../SomeUsefulCommands.html',1,'MiscTopics']]],
  ['sphere_202d_25',['sphere 2d',['../EXA_OPTIMIZATION_THERMAL_FLOW_ABOUT_SPHERE_2D.html',1,'Thermal Flow about a sphere 2D'],['../EXA_OPTIMIZATION_THERMAL_TURBULENT_FLOW_ABOUT_SPHERE_2D.html',1,'Thermal Turbulent Flow about a sphere 2D']]],
  ['sphere_203d_26',['Thermal Flow about a sphere 3D',['../EXA_OPTIMIZATION_THERMAL_FLOW_ABOUT_SPHERE_3D.html',1,'']]],
  ['sqp_27',['Sequential Quadratic Programming (SQP)',['../opt_sqp.html',1,'opt_module']]],
  ['squares_20stabilization_28',['Fickian Problem for Demonstrating Gradient Galerkin Least Squares Stabilization',['../EXA_THERMAL_GGLS_DEMO.html',1,'']]],
  ['stabilization_29',['Fickian Problem for Demonstrating Gradient Galerkin Least Squares Stabilization',['../EXA_THERMAL_GGLS_DEMO.html',1,'']]],
  ['stabilization_20parameter_20for_20convective_20ghost_30',['Stabilization Parameter for Convective Ghost',['../FE_SP_Convective_Ghost.html',1,'']]],
  ['stabilization_20parameter_20for_20dirichlet_20condition_20via_20nitsche_20formulation_31',['Stabilization Parameter for Dirichlet condition via Nitsche formulation',['../FE_SP_Dirichlet_Nitsche.html',1,'']]],
  ['stabilization_20parameter_20for_20dirichlet_20on_20modified_20viscosity_20via_20nitsche_32',['Stabilization Parameter for Dirichlet on Modified Viscosity via Nitsche',['../FE_SP_Spalart_Allmaras_Dirichlet_Nitsche.html',1,'']]],
  ['stabilization_20parameter_20for_20dirichlet_20on_20velocity_20via_20nitsche_33',['Stabilization Parameter for Dirichlet on Velocity via Nitsche',['../FE_SP_Velocity_Dirichlet_Nitsche.html',1,'']]],
  ['stabilization_20parameter_20for_20follower_20weight_20in_20interface_20condition_34',['Stabilization Parameter for Follower Weight in Interface condition',['../FE_SP_Follower_Weight_Interface.html',1,'']]],
  ['stabilization_20parameter_20for_20ghost_20on_20field_35',['Stabilization Parameter for Ghost on Field',['../FE_SP_Ghost_Field.html',1,'']]],
  ['stabilization_20parameter_20for_20interface_20condition_20via_20nitsche_20formulation_36',['Stabilization Parameter for Interface condition via Nitsche formulation',['../FE_SP_Nitsche_Interface.html',1,'']]],
  ['stabilization_20parameter_20for_20leader_20weight_20in_20interface_20condition_37',['Stabilization Parameter for Leader Weight in Interface condition',['../FE_SP_Leader_Weight_Interface.html',1,'']]],
  ['stabilization_20parameter_20for_20pressure_20ghost_38',['Stabilization Parameter for Pressure Ghost',['../FE_SP_Pressure_Ghost.html',1,'']]],
  ['stabilization_20parameter_20for_20supg_20stabilization_20in_20incompressible_20navier_20stokes_39',['Stabilization Parameter for SUPG stabilization in Incompressible Navier-Stokes',['../FE_SP_Incompressible_NS.html',1,'']]],
  ['stabilization_20parameter_20for_20time_20velocity_20ghost_40',['Stabilization Parameter for Time Velocity Ghost',['../FE_SP_Time_Velocity_Ghost.html',1,'']]],
  ['stabilization_20parameter_20for_20viscous_20ghost_41',['Stabilization Parameter for Viscous Ghost',['../FE_SP_Viscous_Ghost.html',1,'']]],
  ['started_42',['Getting Started',['../GettingStarted.html',1,'']]],
  ['static_43',['static',['../EXA_Channel_2D_Static.html',1,'Channel 2D Static'],['../EXA_THERMAL_ADVECTION_CHANNEL_WITH_FOUR_CYLINDERS_STATIC.html',1,'Channel with Four Cylinders Static'],['../EXA_Couette_Flow_Static.html',1,'Couette Flow Static'],['../EXA_Single_Phase_Hollow_Cylinder_Static.html',1,'Single Phase Hollow Cylinder Static']]],
  ['static_20problem_44',['SA Cut Bar Static Problem',['../EXA_OPTIMIZATION_SA_CUT_BAR_STATIC.html',1,'']]],
  ['static_20temperature_20only_45',['Channel with Four Cylinders Static Temperature only',['../EXA_Thermal_Diffusion_Channel_with_Four_Cylinders_Static_Temp_Only.html',1,'']]],
  ['stefan_20s_20problem_20for_20diffusion_20with_20phase_20change_46',['Stefan&apos;s Problem for Diffusion with Phase Change',['../EXA_THERMAL_STEFANS_PROBLEM.html',1,'']]],
  ['stk_5fxtk_5fheatconduction_47',['STK_XTK_HeatConduction',['../EXA_Structure_Linear_STK_XTK_HeatConduction.html',1,'']]],
  ['stokes_48',['Stabilization Parameter for SUPG stabilization in Incompressible Navier-Stokes',['../FE_SP_Incompressible_NS.html',1,'']]],
  ['strain_20problem_49',['Plane Strain Problem.',['../EXA_Structure_Linear_Plane_Strain.html',1,'']]],
  ['supg_20stabilization_20in_20incompressible_20navier_20stokes_50',['Stabilization Parameter for SUPG stabilization in Incompressible Navier-Stokes',['../FE_SP_Incompressible_NS.html',1,'']]],
  ['svn_51',['Why SVN?',['../SVNTopics.html',1,'MiscTopics']]],
  ['sweep_52',['sweep',['../opt_sweep.html',1,'Design Variable Sweep'],['../EXA_Shape_Sensitivity_Sweep.html',1,'Shape Sensitivity Circle Sweep'],['../EXA_Shape_Sensitivity_Bspline.html',1,'Shape Sensitivity Circle Sweep']]]
];
